/*
Copyright 2020 The OpenShift Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	artv1alpha1 "github.com/vfreex/release-apiserver/pkg/apis/art/v1alpha1"
	clientset "github.com/vfreex/release-apiserver/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/vfreex/release-apiserver/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/vfreex/release-apiserver/pkg/client/listers_generated/art/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RPMComposeInformer provides access to a shared informer and lister for
// RPMComposes.
type RPMComposeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RPMComposeLister
}

type rPMComposeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRPMComposeInformer constructs a new informer for RPMCompose type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRPMComposeInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRPMComposeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRPMComposeInformer constructs a new informer for RPMCompose type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRPMComposeInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArtV1alpha1().RPMComposes(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArtV1alpha1().RPMComposes(namespace).Watch(options)
			},
		},
		&artv1alpha1.RPMCompose{},
		resyncPeriod,
		indexers,
	)
}

func (f *rPMComposeInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRPMComposeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *rPMComposeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&artv1alpha1.RPMCompose{}, f.defaultInformer)
}

func (f *rPMComposeInformer) Lister() v1alpha1.RPMComposeLister {
	return v1alpha1.NewRPMComposeLister(f.Informer().GetIndexer())
}
