// +build !ignore_autogenerated

/*
Copyright 2020 The OpenShift Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	release "github.com/vfreex/release-apiserver/pkg/apis/release"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ReleaseStream)(nil), (*release.ReleaseStream)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseStream_To_release_ReleaseStream(a.(*ReleaseStream), b.(*release.ReleaseStream), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*release.ReleaseStream)(nil), (*ReleaseStream)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_release_ReleaseStream_To_v1alpha1_ReleaseStream(a.(*release.ReleaseStream), b.(*ReleaseStream), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseStreamGitSource)(nil), (*release.ReleaseStreamGitSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseStreamGitSource_To_release_ReleaseStreamGitSource(a.(*ReleaseStreamGitSource), b.(*release.ReleaseStreamGitSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*release.ReleaseStreamGitSource)(nil), (*ReleaseStreamGitSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_release_ReleaseStreamGitSource_To_v1alpha1_ReleaseStreamGitSource(a.(*release.ReleaseStreamGitSource), b.(*ReleaseStreamGitSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseStreamList)(nil), (*release.ReleaseStreamList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseStreamList_To_release_ReleaseStreamList(a.(*ReleaseStreamList), b.(*release.ReleaseStreamList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*release.ReleaseStreamList)(nil), (*ReleaseStreamList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_release_ReleaseStreamList_To_v1alpha1_ReleaseStreamList(a.(*release.ReleaseStreamList), b.(*ReleaseStreamList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseStreamOcpBuildData)(nil), (*release.ReleaseStreamOcpBuildData)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseStreamOcpBuildData_To_release_ReleaseStreamOcpBuildData(a.(*ReleaseStreamOcpBuildData), b.(*release.ReleaseStreamOcpBuildData), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*release.ReleaseStreamOcpBuildData)(nil), (*ReleaseStreamOcpBuildData)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_release_ReleaseStreamOcpBuildData_To_v1alpha1_ReleaseStreamOcpBuildData(a.(*release.ReleaseStreamOcpBuildData), b.(*ReleaseStreamOcpBuildData), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseStreamSpec)(nil), (*release.ReleaseStreamSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseStreamSpec_To_release_ReleaseStreamSpec(a.(*ReleaseStreamSpec), b.(*release.ReleaseStreamSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*release.ReleaseStreamSpec)(nil), (*ReleaseStreamSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_release_ReleaseStreamSpec_To_v1alpha1_ReleaseStreamSpec(a.(*release.ReleaseStreamSpec), b.(*ReleaseStreamSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseStreamStatus)(nil), (*release.ReleaseStreamStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseStreamStatus_To_release_ReleaseStreamStatus(a.(*ReleaseStreamStatus), b.(*release.ReleaseStreamStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*release.ReleaseStreamStatus)(nil), (*ReleaseStreamStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_release_ReleaseStreamStatus_To_v1alpha1_ReleaseStreamStatus(a.(*release.ReleaseStreamStatus), b.(*ReleaseStreamStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ReleaseStream_To_release_ReleaseStream(in *ReleaseStream, out *release.ReleaseStream, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ReleaseStreamSpec_To_release_ReleaseStreamSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ReleaseStreamStatus_To_release_ReleaseStreamStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ReleaseStream_To_release_ReleaseStream is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseStream_To_release_ReleaseStream(in *ReleaseStream, out *release.ReleaseStream, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseStream_To_release_ReleaseStream(in, out, s)
}

func autoConvert_release_ReleaseStream_To_v1alpha1_ReleaseStream(in *release.ReleaseStream, out *ReleaseStream, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_release_ReleaseStreamSpec_To_v1alpha1_ReleaseStreamSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_release_ReleaseStreamStatus_To_v1alpha1_ReleaseStreamStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_release_ReleaseStream_To_v1alpha1_ReleaseStream is an autogenerated conversion function.
func Convert_release_ReleaseStream_To_v1alpha1_ReleaseStream(in *release.ReleaseStream, out *ReleaseStream, s conversion.Scope) error {
	return autoConvert_release_ReleaseStream_To_v1alpha1_ReleaseStream(in, out, s)
}

func autoConvert_v1alpha1_ReleaseStreamGitSource_To_release_ReleaseStreamGitSource(in *ReleaseStreamGitSource, out *release.ReleaseStreamGitSource, s conversion.Scope) error {
	out.Url = in.Url
	out.Ref = in.Ref
	out.Path = in.Path
	return nil
}

// Convert_v1alpha1_ReleaseStreamGitSource_To_release_ReleaseStreamGitSource is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseStreamGitSource_To_release_ReleaseStreamGitSource(in *ReleaseStreamGitSource, out *release.ReleaseStreamGitSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseStreamGitSource_To_release_ReleaseStreamGitSource(in, out, s)
}

func autoConvert_release_ReleaseStreamGitSource_To_v1alpha1_ReleaseStreamGitSource(in *release.ReleaseStreamGitSource, out *ReleaseStreamGitSource, s conversion.Scope) error {
	out.Url = in.Url
	out.Ref = in.Ref
	out.Path = in.Path
	return nil
}

// Convert_release_ReleaseStreamGitSource_To_v1alpha1_ReleaseStreamGitSource is an autogenerated conversion function.
func Convert_release_ReleaseStreamGitSource_To_v1alpha1_ReleaseStreamGitSource(in *release.ReleaseStreamGitSource, out *ReleaseStreamGitSource, s conversion.Scope) error {
	return autoConvert_release_ReleaseStreamGitSource_To_v1alpha1_ReleaseStreamGitSource(in, out, s)
}

func autoConvert_v1alpha1_ReleaseStreamList_To_release_ReleaseStreamList(in *ReleaseStreamList, out *release.ReleaseStreamList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]release.ReleaseStream)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ReleaseStreamList_To_release_ReleaseStreamList is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseStreamList_To_release_ReleaseStreamList(in *ReleaseStreamList, out *release.ReleaseStreamList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseStreamList_To_release_ReleaseStreamList(in, out, s)
}

func autoConvert_release_ReleaseStreamList_To_v1alpha1_ReleaseStreamList(in *release.ReleaseStreamList, out *ReleaseStreamList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ReleaseStream)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_release_ReleaseStreamList_To_v1alpha1_ReleaseStreamList is an autogenerated conversion function.
func Convert_release_ReleaseStreamList_To_v1alpha1_ReleaseStreamList(in *release.ReleaseStreamList, out *ReleaseStreamList, s conversion.Scope) error {
	return autoConvert_release_ReleaseStreamList_To_v1alpha1_ReleaseStreamList(in, out, s)
}

func autoConvert_v1alpha1_ReleaseStreamOcpBuildData_To_release_ReleaseStreamOcpBuildData(in *ReleaseStreamOcpBuildData, out *release.ReleaseStreamOcpBuildData, s conversion.Scope) error {
	if err := Convert_v1alpha1_ReleaseStreamGitSource_To_release_ReleaseStreamGitSource(&in.Git, &out.Git, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ReleaseStreamOcpBuildData_To_release_ReleaseStreamOcpBuildData is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseStreamOcpBuildData_To_release_ReleaseStreamOcpBuildData(in *ReleaseStreamOcpBuildData, out *release.ReleaseStreamOcpBuildData, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseStreamOcpBuildData_To_release_ReleaseStreamOcpBuildData(in, out, s)
}

func autoConvert_release_ReleaseStreamOcpBuildData_To_v1alpha1_ReleaseStreamOcpBuildData(in *release.ReleaseStreamOcpBuildData, out *ReleaseStreamOcpBuildData, s conversion.Scope) error {
	if err := Convert_release_ReleaseStreamGitSource_To_v1alpha1_ReleaseStreamGitSource(&in.Git, &out.Git, s); err != nil {
		return err
	}
	return nil
}

// Convert_release_ReleaseStreamOcpBuildData_To_v1alpha1_ReleaseStreamOcpBuildData is an autogenerated conversion function.
func Convert_release_ReleaseStreamOcpBuildData_To_v1alpha1_ReleaseStreamOcpBuildData(in *release.ReleaseStreamOcpBuildData, out *ReleaseStreamOcpBuildData, s conversion.Scope) error {
	return autoConvert_release_ReleaseStreamOcpBuildData_To_v1alpha1_ReleaseStreamOcpBuildData(in, out, s)
}

func autoConvert_v1alpha1_ReleaseStreamSpec_To_release_ReleaseStreamSpec(in *ReleaseStreamSpec, out *release.ReleaseStreamSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ReleaseStreamOcpBuildData_To_release_ReleaseStreamOcpBuildData(&in.OcpBuildData, &out.OcpBuildData, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ReleaseStreamSpec_To_release_ReleaseStreamSpec is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseStreamSpec_To_release_ReleaseStreamSpec(in *ReleaseStreamSpec, out *release.ReleaseStreamSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseStreamSpec_To_release_ReleaseStreamSpec(in, out, s)
}

func autoConvert_release_ReleaseStreamSpec_To_v1alpha1_ReleaseStreamSpec(in *release.ReleaseStreamSpec, out *ReleaseStreamSpec, s conversion.Scope) error {
	if err := Convert_release_ReleaseStreamOcpBuildData_To_v1alpha1_ReleaseStreamOcpBuildData(&in.OcpBuildData, &out.OcpBuildData, s); err != nil {
		return err
	}
	return nil
}

// Convert_release_ReleaseStreamSpec_To_v1alpha1_ReleaseStreamSpec is an autogenerated conversion function.
func Convert_release_ReleaseStreamSpec_To_v1alpha1_ReleaseStreamSpec(in *release.ReleaseStreamSpec, out *ReleaseStreamSpec, s conversion.Scope) error {
	return autoConvert_release_ReleaseStreamSpec_To_v1alpha1_ReleaseStreamSpec(in, out, s)
}

func autoConvert_v1alpha1_ReleaseStreamStatus_To_release_ReleaseStreamStatus(in *ReleaseStreamStatus, out *release.ReleaseStreamStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ReleaseStreamStatus_To_release_ReleaseStreamStatus is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseStreamStatus_To_release_ReleaseStreamStatus(in *ReleaseStreamStatus, out *release.ReleaseStreamStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseStreamStatus_To_release_ReleaseStreamStatus(in, out, s)
}

func autoConvert_release_ReleaseStreamStatus_To_v1alpha1_ReleaseStreamStatus(in *release.ReleaseStreamStatus, out *ReleaseStreamStatus, s conversion.Scope) error {
	return nil
}

// Convert_release_ReleaseStreamStatus_To_v1alpha1_ReleaseStreamStatus is an autogenerated conversion function.
func Convert_release_ReleaseStreamStatus_To_v1alpha1_ReleaseStreamStatus(in *release.ReleaseStreamStatus, out *ReleaseStreamStatus, s conversion.Scope) error {
	return autoConvert_release_ReleaseStreamStatus_To_v1alpha1_ReleaseStreamStatus(in, out, s)
}
