/*
Copyright 2020 The OCP Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	proxyv1alpha1 "github.com/vfreex/release-apiserver/pkg/apis/proxy/v1alpha1"
	clientset "github.com/vfreex/release-apiserver/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/vfreex/release-apiserver/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/vfreex/release-apiserver/pkg/client/listers_generated/proxy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KojiImageBuildPackageInformer provides access to a shared informer and lister for
// KojiImageBuildPackages.
type KojiImageBuildPackageInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.KojiImageBuildPackageLister
}

type kojiImageBuildPackageInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKojiImageBuildPackageInformer constructs a new informer for KojiImageBuildPackage type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKojiImageBuildPackageInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKojiImageBuildPackageInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKojiImageBuildPackageInformer constructs a new informer for KojiImageBuildPackage type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKojiImageBuildPackageInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ProxyV1alpha1().KojiImageBuildPackages(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ProxyV1alpha1().KojiImageBuildPackages(namespace).Watch(options)
			},
		},
		&proxyv1alpha1.KojiImageBuildPackage{},
		resyncPeriod,
		indexers,
	)
}

func (f *kojiImageBuildPackageInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKojiImageBuildPackageInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kojiImageBuildPackageInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&proxyv1alpha1.KojiImageBuildPackage{}, f.defaultInformer)
}

func (f *kojiImageBuildPackageInformer) Lister() v1alpha1.KojiImageBuildPackageLister {
	return v1alpha1.NewKojiImageBuildPackageLister(f.Informer().GetIndexer())
}
