/*
Copyright 2020 The OpenShift Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vfreex/release-apiserver/pkg/apis/release/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePayloads implements PayloadInterface
type FakePayloads struct {
	Fake *FakeReleaseV1alpha1
	ns   string
}

var payloadsResource = schema.GroupVersionResource{Group: "release.art.openshift.io", Version: "v1alpha1", Resource: "payloads"}

var payloadsKind = schema.GroupVersionKind{Group: "release.art.openshift.io", Version: "v1alpha1", Kind: "Payload"}

// Get takes name of the payload, and returns the corresponding payload object, and an error if there is any.
func (c *FakePayloads) Get(name string, options v1.GetOptions) (result *v1alpha1.Payload, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(payloadsResource, c.ns, name), &v1alpha1.Payload{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Payload), err
}

// List takes label and field selectors, and returns the list of Payloads that match those selectors.
func (c *FakePayloads) List(opts v1.ListOptions) (result *v1alpha1.PayloadList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(payloadsResource, payloadsKind, c.ns, opts), &v1alpha1.PayloadList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PayloadList{ListMeta: obj.(*v1alpha1.PayloadList).ListMeta}
	for _, item := range obj.(*v1alpha1.PayloadList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested payloads.
func (c *FakePayloads) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(payloadsResource, c.ns, opts))

}

// Create takes the representation of a payload and creates it.  Returns the server's representation of the payload, and an error, if there is any.
func (c *FakePayloads) Create(payload *v1alpha1.Payload) (result *v1alpha1.Payload, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(payloadsResource, c.ns, payload), &v1alpha1.Payload{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Payload), err
}

// Update takes the representation of a payload and updates it. Returns the server's representation of the payload, and an error, if there is any.
func (c *FakePayloads) Update(payload *v1alpha1.Payload) (result *v1alpha1.Payload, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(payloadsResource, c.ns, payload), &v1alpha1.Payload{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Payload), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePayloads) UpdateStatus(payload *v1alpha1.Payload) (*v1alpha1.Payload, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(payloadsResource, "status", c.ns, payload), &v1alpha1.Payload{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Payload), err
}

// Delete takes name of the payload and deletes it. Returns an error if one occurs.
func (c *FakePayloads) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(payloadsResource, c.ns, name), &v1alpha1.Payload{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePayloads) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(payloadsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PayloadList{})
	return err
}

// Patch applies the patch and returns the patched payload.
func (c *FakePayloads) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Payload, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(payloadsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Payload{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Payload), err
}
