/*
Copyright 2020 The OpenShift Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vfreex/release-apiserver/pkg/apis/release/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAdvisories implements AdvisoryInterface
type FakeAdvisories struct {
	Fake *FakeReleaseV1alpha1
	ns   string
}

var advisoriesResource = schema.GroupVersionResource{Group: "release.art.openshift.io", Version: "v1alpha1", Resource: "advisories"}

var advisoriesKind = schema.GroupVersionKind{Group: "release.art.openshift.io", Version: "v1alpha1", Kind: "Advisory"}

// Get takes name of the advisory, and returns the corresponding advisory object, and an error if there is any.
func (c *FakeAdvisories) Get(name string, options v1.GetOptions) (result *v1alpha1.Advisory, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(advisoriesResource, c.ns, name), &v1alpha1.Advisory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Advisory), err
}

// List takes label and field selectors, and returns the list of Advisories that match those selectors.
func (c *FakeAdvisories) List(opts v1.ListOptions) (result *v1alpha1.AdvisoryList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(advisoriesResource, advisoriesKind, c.ns, opts), &v1alpha1.AdvisoryList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AdvisoryList{ListMeta: obj.(*v1alpha1.AdvisoryList).ListMeta}
	for _, item := range obj.(*v1alpha1.AdvisoryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested advisories.
func (c *FakeAdvisories) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(advisoriesResource, c.ns, opts))

}

// Create takes the representation of a advisory and creates it.  Returns the server's representation of the advisory, and an error, if there is any.
func (c *FakeAdvisories) Create(advisory *v1alpha1.Advisory) (result *v1alpha1.Advisory, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(advisoriesResource, c.ns, advisory), &v1alpha1.Advisory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Advisory), err
}

// Update takes the representation of a advisory and updates it. Returns the server's representation of the advisory, and an error, if there is any.
func (c *FakeAdvisories) Update(advisory *v1alpha1.Advisory) (result *v1alpha1.Advisory, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(advisoriesResource, c.ns, advisory), &v1alpha1.Advisory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Advisory), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAdvisories) UpdateStatus(advisory *v1alpha1.Advisory) (*v1alpha1.Advisory, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(advisoriesResource, "status", c.ns, advisory), &v1alpha1.Advisory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Advisory), err
}

// Delete takes name of the advisory and deletes it. Returns an error if one occurs.
func (c *FakeAdvisories) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(advisoriesResource, c.ns, name), &v1alpha1.Advisory{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAdvisories) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(advisoriesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AdvisoryList{})
	return err
}

// Patch applies the patch and returns the patched advisory.
func (c *FakeAdvisories) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Advisory, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(advisoriesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Advisory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Advisory), err
}
