# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openshift_release
from openshift_release.models.io_k8s_apimachinery_pkg_version_info import IoK8sApimachineryPkgVersionInfo  # noqa: E501
from openshift_release.rest import ApiException

class TestIoK8sApimachineryPkgVersionInfo(unittest.TestCase):
    """IoK8sApimachineryPkgVersionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IoK8sApimachineryPkgVersionInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openshift_release.models.io_k8s_apimachinery_pkg_version_info.IoK8sApimachineryPkgVersionInfo()  # noqa: E501
        if include_optional :
            return IoK8sApimachineryPkgVersionInfo(
                build_date = '0', 
                compiler = '0', 
                git_commit = '0', 
                git_tree_state = '0', 
                git_version = '0', 
                go_version = '0', 
                major = '0', 
                minor = '0', 
                platform = '0'
            )
        else :
            return IoK8sApimachineryPkgVersionInfo(
                build_date = '0',
                compiler = '0',
                git_commit = '0',
                git_tree_state = '0',
                git_version = '0',
                go_version = '0',
                major = '0',
                minor = '0',
                platform = '0',
        )

    def testIoK8sApimachineryPkgVersionInfo(self):
        """Test IoK8sApimachineryPkgVersionInfo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
