# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openshift_release
from openshift_release.models.io_k8s_apimachinery_pkg_apis_meta_v1_list_meta import IoK8sApimachineryPkgApisMetaV1ListMeta  # noqa: E501
from openshift_release.rest import ApiException

class TestIoK8sApimachineryPkgApisMetaV1ListMeta(unittest.TestCase):
    """IoK8sApimachineryPkgApisMetaV1ListMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IoK8sApimachineryPkgApisMetaV1ListMeta
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openshift_release.models.io_k8s_apimachinery_pkg_apis_meta_v1_list_meta.IoK8sApimachineryPkgApisMetaV1ListMeta()  # noqa: E501
        if include_optional :
            return IoK8sApimachineryPkgApisMetaV1ListMeta(
                _continue = '0', 
                remaining_item_count = 56, 
                resource_version = '0', 
                self_link = '0'
            )
        else :
            return IoK8sApimachineryPkgApisMetaV1ListMeta(
        )

    def testIoK8sApimachineryPkgApisMetaV1ListMeta(self):
        """Test IoK8sApimachineryPkgApisMetaV1ListMeta"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
