# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openshift_release
from openshift_release.api.art_openshift_io_v1alpha1_api import ArtOpenshiftIoV1alpha1Api  # noqa: E501
from openshift_release.rest import ApiException


class TestArtOpenshiftIoV1alpha1Api(unittest.TestCase):
    """ArtOpenshiftIoV1alpha1Api unit test stubs"""

    def setUp(self):
        self.api = openshift_release.api.art_openshift_io_v1alpha1_api.ArtOpenshiftIoV1alpha1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_art_openshift_io_v1alpha1_namespaced_advisory(self):
        """Test case for create_art_openshift_io_v1alpha1_namespaced_advisory

        """
        pass

    def test_create_art_openshift_io_v1alpha1_namespaced_advisory_status(self):
        """Test case for create_art_openshift_io_v1alpha1_namespaced_advisory_status

        """
        pass

    def test_create_art_openshift_io_v1alpha1_namespaced_build(self):
        """Test case for create_art_openshift_io_v1alpha1_namespaced_build

        """
        pass

    def test_create_art_openshift_io_v1alpha1_namespaced_build_status(self):
        """Test case for create_art_openshift_io_v1alpha1_namespaced_build_status

        """
        pass

    def test_create_art_openshift_io_v1alpha1_namespaced_component(self):
        """Test case for create_art_openshift_io_v1alpha1_namespaced_component

        """
        pass

    def test_create_art_openshift_io_v1alpha1_namespaced_component_status(self):
        """Test case for create_art_openshift_io_v1alpha1_namespaced_component_status

        """
        pass

    def test_create_art_openshift_io_v1alpha1_namespaced_release(self):
        """Test case for create_art_openshift_io_v1alpha1_namespaced_release

        """
        pass

    def test_create_art_openshift_io_v1alpha1_namespaced_release_status(self):
        """Test case for create_art_openshift_io_v1alpha1_namespaced_release_status

        """
        pass

    def test_create_art_openshift_io_v1alpha1_namespaced_release_stream(self):
        """Test case for create_art_openshift_io_v1alpha1_namespaced_release_stream

        """
        pass

    def test_create_art_openshift_io_v1alpha1_namespaced_release_stream_status(self):
        """Test case for create_art_openshift_io_v1alpha1_namespaced_release_stream_status

        """
        pass

    def test_create_art_openshift_io_v1alpha1_namespaced_rpm_compose(self):
        """Test case for create_art_openshift_io_v1alpha1_namespaced_rpm_compose

        """
        pass

    def test_create_art_openshift_io_v1alpha1_namespaced_rpm_compose_status(self):
        """Test case for create_art_openshift_io_v1alpha1_namespaced_rpm_compose_status

        """
        pass

    def test_create_art_openshift_io_v1alpha1_namespaced_source_revision(self):
        """Test case for create_art_openshift_io_v1alpha1_namespaced_source_revision

        """
        pass

    def test_create_art_openshift_io_v1alpha1_namespaced_source_revision_status(self):
        """Test case for create_art_openshift_io_v1alpha1_namespaced_source_revision_status

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_collection_namespaced_advisory(self):
        """Test case for delete_art_openshift_io_v1alpha1_collection_namespaced_advisory

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_collection_namespaced_build(self):
        """Test case for delete_art_openshift_io_v1alpha1_collection_namespaced_build

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_collection_namespaced_component(self):
        """Test case for delete_art_openshift_io_v1alpha1_collection_namespaced_component

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_collection_namespaced_release(self):
        """Test case for delete_art_openshift_io_v1alpha1_collection_namespaced_release

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_collection_namespaced_release_stream(self):
        """Test case for delete_art_openshift_io_v1alpha1_collection_namespaced_release_stream

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_collection_namespaced_rpm_compose(self):
        """Test case for delete_art_openshift_io_v1alpha1_collection_namespaced_rpm_compose

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_collection_namespaced_source_revision(self):
        """Test case for delete_art_openshift_io_v1alpha1_collection_namespaced_source_revision

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_namespaced_advisory(self):
        """Test case for delete_art_openshift_io_v1alpha1_namespaced_advisory

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_namespaced_advisory_status(self):
        """Test case for delete_art_openshift_io_v1alpha1_namespaced_advisory_status

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_namespaced_build(self):
        """Test case for delete_art_openshift_io_v1alpha1_namespaced_build

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_namespaced_build_status(self):
        """Test case for delete_art_openshift_io_v1alpha1_namespaced_build_status

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_namespaced_component(self):
        """Test case for delete_art_openshift_io_v1alpha1_namespaced_component

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_namespaced_component_status(self):
        """Test case for delete_art_openshift_io_v1alpha1_namespaced_component_status

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_namespaced_release(self):
        """Test case for delete_art_openshift_io_v1alpha1_namespaced_release

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_namespaced_release_status(self):
        """Test case for delete_art_openshift_io_v1alpha1_namespaced_release_status

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_namespaced_release_stream(self):
        """Test case for delete_art_openshift_io_v1alpha1_namespaced_release_stream

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_namespaced_release_stream_status(self):
        """Test case for delete_art_openshift_io_v1alpha1_namespaced_release_stream_status

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_namespaced_rpm_compose(self):
        """Test case for delete_art_openshift_io_v1alpha1_namespaced_rpm_compose

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_namespaced_rpm_compose_status(self):
        """Test case for delete_art_openshift_io_v1alpha1_namespaced_rpm_compose_status

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_namespaced_source_revision(self):
        """Test case for delete_art_openshift_io_v1alpha1_namespaced_source_revision

        """
        pass

    def test_delete_art_openshift_io_v1alpha1_namespaced_source_revision_status(self):
        """Test case for delete_art_openshift_io_v1alpha1_namespaced_source_revision_status

        """
        pass

    def test_get_art_openshift_io_v1alpha1_api_resources(self):
        """Test case for get_art_openshift_io_v1alpha1_api_resources

        """
        pass

    def test_list_art_openshift_io_v1alpha1_advisory_for_all_namespaces(self):
        """Test case for list_art_openshift_io_v1alpha1_advisory_for_all_namespaces

        """
        pass

    def test_list_art_openshift_io_v1alpha1_build_for_all_namespaces(self):
        """Test case for list_art_openshift_io_v1alpha1_build_for_all_namespaces

        """
        pass

    def test_list_art_openshift_io_v1alpha1_component_for_all_namespaces(self):
        """Test case for list_art_openshift_io_v1alpha1_component_for_all_namespaces

        """
        pass

    def test_list_art_openshift_io_v1alpha1_namespaced_advisory(self):
        """Test case for list_art_openshift_io_v1alpha1_namespaced_advisory

        """
        pass

    def test_list_art_openshift_io_v1alpha1_namespaced_build(self):
        """Test case for list_art_openshift_io_v1alpha1_namespaced_build

        """
        pass

    def test_list_art_openshift_io_v1alpha1_namespaced_component(self):
        """Test case for list_art_openshift_io_v1alpha1_namespaced_component

        """
        pass

    def test_list_art_openshift_io_v1alpha1_namespaced_release(self):
        """Test case for list_art_openshift_io_v1alpha1_namespaced_release

        """
        pass

    def test_list_art_openshift_io_v1alpha1_namespaced_release_stream(self):
        """Test case for list_art_openshift_io_v1alpha1_namespaced_release_stream

        """
        pass

    def test_list_art_openshift_io_v1alpha1_namespaced_rpm_compose(self):
        """Test case for list_art_openshift_io_v1alpha1_namespaced_rpm_compose

        """
        pass

    def test_list_art_openshift_io_v1alpha1_namespaced_source_revision(self):
        """Test case for list_art_openshift_io_v1alpha1_namespaced_source_revision

        """
        pass

    def test_list_art_openshift_io_v1alpha1_release_for_all_namespaces(self):
        """Test case for list_art_openshift_io_v1alpha1_release_for_all_namespaces

        """
        pass

    def test_list_art_openshift_io_v1alpha1_release_stream_for_all_namespaces(self):
        """Test case for list_art_openshift_io_v1alpha1_release_stream_for_all_namespaces

        """
        pass

    def test_list_art_openshift_io_v1alpha1_rpm_compose_for_all_namespaces(self):
        """Test case for list_art_openshift_io_v1alpha1_rpm_compose_for_all_namespaces

        """
        pass

    def test_list_art_openshift_io_v1alpha1_source_revision_for_all_namespaces(self):
        """Test case for list_art_openshift_io_v1alpha1_source_revision_for_all_namespaces

        """
        pass

    def test_patch_art_openshift_io_v1alpha1_namespaced_advisory(self):
        """Test case for patch_art_openshift_io_v1alpha1_namespaced_advisory

        """
        pass

    def test_patch_art_openshift_io_v1alpha1_namespaced_advisory_status(self):
        """Test case for patch_art_openshift_io_v1alpha1_namespaced_advisory_status

        """
        pass

    def test_patch_art_openshift_io_v1alpha1_namespaced_build(self):
        """Test case for patch_art_openshift_io_v1alpha1_namespaced_build

        """
        pass

    def test_patch_art_openshift_io_v1alpha1_namespaced_build_status(self):
        """Test case for patch_art_openshift_io_v1alpha1_namespaced_build_status

        """
        pass

    def test_patch_art_openshift_io_v1alpha1_namespaced_component(self):
        """Test case for patch_art_openshift_io_v1alpha1_namespaced_component

        """
        pass

    def test_patch_art_openshift_io_v1alpha1_namespaced_component_status(self):
        """Test case for patch_art_openshift_io_v1alpha1_namespaced_component_status

        """
        pass

    def test_patch_art_openshift_io_v1alpha1_namespaced_release(self):
        """Test case for patch_art_openshift_io_v1alpha1_namespaced_release

        """
        pass

    def test_patch_art_openshift_io_v1alpha1_namespaced_release_status(self):
        """Test case for patch_art_openshift_io_v1alpha1_namespaced_release_status

        """
        pass

    def test_patch_art_openshift_io_v1alpha1_namespaced_release_stream(self):
        """Test case for patch_art_openshift_io_v1alpha1_namespaced_release_stream

        """
        pass

    def test_patch_art_openshift_io_v1alpha1_namespaced_release_stream_status(self):
        """Test case for patch_art_openshift_io_v1alpha1_namespaced_release_stream_status

        """
        pass

    def test_patch_art_openshift_io_v1alpha1_namespaced_rpm_compose(self):
        """Test case for patch_art_openshift_io_v1alpha1_namespaced_rpm_compose

        """
        pass

    def test_patch_art_openshift_io_v1alpha1_namespaced_rpm_compose_status(self):
        """Test case for patch_art_openshift_io_v1alpha1_namespaced_rpm_compose_status

        """
        pass

    def test_patch_art_openshift_io_v1alpha1_namespaced_source_revision(self):
        """Test case for patch_art_openshift_io_v1alpha1_namespaced_source_revision

        """
        pass

    def test_patch_art_openshift_io_v1alpha1_namespaced_source_revision_status(self):
        """Test case for patch_art_openshift_io_v1alpha1_namespaced_source_revision_status

        """
        pass

    def test_read_art_openshift_io_v1alpha1_namespaced_advisory(self):
        """Test case for read_art_openshift_io_v1alpha1_namespaced_advisory

        """
        pass

    def test_read_art_openshift_io_v1alpha1_namespaced_advisory_status(self):
        """Test case for read_art_openshift_io_v1alpha1_namespaced_advisory_status

        """
        pass

    def test_read_art_openshift_io_v1alpha1_namespaced_build(self):
        """Test case for read_art_openshift_io_v1alpha1_namespaced_build

        """
        pass

    def test_read_art_openshift_io_v1alpha1_namespaced_build_status(self):
        """Test case for read_art_openshift_io_v1alpha1_namespaced_build_status

        """
        pass

    def test_read_art_openshift_io_v1alpha1_namespaced_component(self):
        """Test case for read_art_openshift_io_v1alpha1_namespaced_component

        """
        pass

    def test_read_art_openshift_io_v1alpha1_namespaced_component_status(self):
        """Test case for read_art_openshift_io_v1alpha1_namespaced_component_status

        """
        pass

    def test_read_art_openshift_io_v1alpha1_namespaced_release(self):
        """Test case for read_art_openshift_io_v1alpha1_namespaced_release

        """
        pass

    def test_read_art_openshift_io_v1alpha1_namespaced_release_status(self):
        """Test case for read_art_openshift_io_v1alpha1_namespaced_release_status

        """
        pass

    def test_read_art_openshift_io_v1alpha1_namespaced_release_stream(self):
        """Test case for read_art_openshift_io_v1alpha1_namespaced_release_stream

        """
        pass

    def test_read_art_openshift_io_v1alpha1_namespaced_release_stream_status(self):
        """Test case for read_art_openshift_io_v1alpha1_namespaced_release_stream_status

        """
        pass

    def test_read_art_openshift_io_v1alpha1_namespaced_rpm_compose(self):
        """Test case for read_art_openshift_io_v1alpha1_namespaced_rpm_compose

        """
        pass

    def test_read_art_openshift_io_v1alpha1_namespaced_rpm_compose_status(self):
        """Test case for read_art_openshift_io_v1alpha1_namespaced_rpm_compose_status

        """
        pass

    def test_read_art_openshift_io_v1alpha1_namespaced_source_revision(self):
        """Test case for read_art_openshift_io_v1alpha1_namespaced_source_revision

        """
        pass

    def test_read_art_openshift_io_v1alpha1_namespaced_source_revision_status(self):
        """Test case for read_art_openshift_io_v1alpha1_namespaced_source_revision_status

        """
        pass

    def test_replace_art_openshift_io_v1alpha1_namespaced_advisory(self):
        """Test case for replace_art_openshift_io_v1alpha1_namespaced_advisory

        """
        pass

    def test_replace_art_openshift_io_v1alpha1_namespaced_advisory_status(self):
        """Test case for replace_art_openshift_io_v1alpha1_namespaced_advisory_status

        """
        pass

    def test_replace_art_openshift_io_v1alpha1_namespaced_build(self):
        """Test case for replace_art_openshift_io_v1alpha1_namespaced_build

        """
        pass

    def test_replace_art_openshift_io_v1alpha1_namespaced_build_status(self):
        """Test case for replace_art_openshift_io_v1alpha1_namespaced_build_status

        """
        pass

    def test_replace_art_openshift_io_v1alpha1_namespaced_component(self):
        """Test case for replace_art_openshift_io_v1alpha1_namespaced_component

        """
        pass

    def test_replace_art_openshift_io_v1alpha1_namespaced_component_status(self):
        """Test case for replace_art_openshift_io_v1alpha1_namespaced_component_status

        """
        pass

    def test_replace_art_openshift_io_v1alpha1_namespaced_release(self):
        """Test case for replace_art_openshift_io_v1alpha1_namespaced_release

        """
        pass

    def test_replace_art_openshift_io_v1alpha1_namespaced_release_status(self):
        """Test case for replace_art_openshift_io_v1alpha1_namespaced_release_status

        """
        pass

    def test_replace_art_openshift_io_v1alpha1_namespaced_release_stream(self):
        """Test case for replace_art_openshift_io_v1alpha1_namespaced_release_stream

        """
        pass

    def test_replace_art_openshift_io_v1alpha1_namespaced_release_stream_status(self):
        """Test case for replace_art_openshift_io_v1alpha1_namespaced_release_stream_status

        """
        pass

    def test_replace_art_openshift_io_v1alpha1_namespaced_rpm_compose(self):
        """Test case for replace_art_openshift_io_v1alpha1_namespaced_rpm_compose

        """
        pass

    def test_replace_art_openshift_io_v1alpha1_namespaced_rpm_compose_status(self):
        """Test case for replace_art_openshift_io_v1alpha1_namespaced_rpm_compose_status

        """
        pass

    def test_replace_art_openshift_io_v1alpha1_namespaced_source_revision(self):
        """Test case for replace_art_openshift_io_v1alpha1_namespaced_source_revision

        """
        pass

    def test_replace_art_openshift_io_v1alpha1_namespaced_source_revision_status(self):
        """Test case for replace_art_openshift_io_v1alpha1_namespaced_source_revision_status

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_advisory_list_for_all_namespaces(self):
        """Test case for watch_art_openshift_io_v1alpha1_advisory_list_for_all_namespaces

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_build_list_for_all_namespaces(self):
        """Test case for watch_art_openshift_io_v1alpha1_build_list_for_all_namespaces

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_component_list_for_all_namespaces(self):
        """Test case for watch_art_openshift_io_v1alpha1_component_list_for_all_namespaces

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_advisory(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_advisory

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_advisory_list(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_advisory_list

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_advisory_status(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_advisory_status

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_build(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_build

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_build_list(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_build_list

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_build_status(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_build_status

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_component(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_component

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_component_list(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_component_list

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_component_status(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_component_status

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_release(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_release

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_release_list(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_release_list

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_release_status(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_release_status

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_release_stream(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_release_stream

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_release_stream_list(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_release_stream_list

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_release_stream_status(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_release_stream_status

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_rpm_compose(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_rpm_compose

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_rpm_compose_list(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_rpm_compose_list

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_rpm_compose_status(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_rpm_compose_status

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_source_revision(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_source_revision

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_source_revision_list(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_source_revision_list

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_namespaced_source_revision_status(self):
        """Test case for watch_art_openshift_io_v1alpha1_namespaced_source_revision_status

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_release_list_for_all_namespaces(self):
        """Test case for watch_art_openshift_io_v1alpha1_release_list_for_all_namespaces

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_release_stream_list_for_all_namespaces(self):
        """Test case for watch_art_openshift_io_v1alpha1_release_stream_list_for_all_namespaces

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_rpm_compose_list_for_all_namespaces(self):
        """Test case for watch_art_openshift_io_v1alpha1_rpm_compose_list_for_all_namespaces

        """
        pass

    def test_watch_art_openshift_io_v1alpha1_source_revision_list_for_all_namespaces(self):
        """Test case for watch_art_openshift_io_v1alpha1_source_revision_list_for_all_namespaces

        """
        pass


if __name__ == '__main__':
    unittest.main()
