# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openshift_release
from openshift_release.models.com_github_vfreex_release_apiserver_pkg_apis_art_v1alpha1_component_spec import ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ComponentSpec  # noqa: E501
from openshift_release.rest import ApiException

class TestComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ComponentSpec(unittest.TestCase):
    """ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ComponentSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ComponentSpec
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openshift_release.models.com_github_vfreex_release_apiserver_pkg_apis_art_v1alpha1_component_spec.ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ComponentSpec()  # noqa: E501
        if include_optional :
            return ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ComponentSpec(
                dist_git = openshift_release.models.com/github/vfreex/release_apiserver/pkg/apis/art/v1alpha1/component_dist_git.com.github.vfreex.release-apiserver.pkg.apis.art.v1alpha1.ComponentDistGit(
                    instance = '0', 
                    namespace = '0', 
                    repository = '0', ), 
                image = openshift_release.models.com/github/vfreex/release_apiserver/pkg/apis/art/v1alpha1/component_image.com.github.vfreex.release-apiserver.pkg.apis.art.v1alpha1.ComponentImage(
                    namespace = '0', 
                    repository = '0', ), 
                kind = '0', 
                source = openshift_release.models.com/github/vfreex/release_apiserver/pkg/apis/art/v1alpha1/component_source.com.github.vfreex.release-apiserver.pkg.apis.art.v1alpha1.ComponentSource(
                    git = openshift_release.models.com/github/vfreex/release_apiserver/pkg/apis/art/v1alpha1/component_git_source.com.github.vfreex.release-apiserver.pkg.apis.art.v1alpha1.ComponentGitSource(
                        fallback_ref = '0', 
                        path = '0', 
                        ref = '0', 
                        url = '0', ), )
            )
        else :
            return ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ComponentSpec(
        )

    def testComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ComponentSpec(self):
        """Test ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ComponentSpec"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
