# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openshift_release
from openshift_release.api.art_openshift_io_api import ArtOpenshiftIoApi  # noqa: E501
from openshift_release.rest import ApiException


class TestArtOpenshiftIoApi(unittest.TestCase):
    """ArtOpenshiftIoApi unit test stubs"""

    def setUp(self):
        self.api = openshift_release.api.art_openshift_io_api.ArtOpenshiftIoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_art_openshift_io_api_group(self):
        """Test case for get_art_openshift_io_api_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
