/*
Copyright 2020 The OpenShift Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/vfreex/release-apiserver/pkg/apis/release/v1alpha1"
	scheme "github.com/vfreex/release-apiserver/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PayloadsGetter has a method to return a PayloadInterface.
// A group's client should implement this interface.
type PayloadsGetter interface {
	Payloads(namespace string) PayloadInterface
}

// PayloadInterface has methods to work with Payload resources.
type PayloadInterface interface {
	Create(*v1alpha1.Payload) (*v1alpha1.Payload, error)
	Update(*v1alpha1.Payload) (*v1alpha1.Payload, error)
	UpdateStatus(*v1alpha1.Payload) (*v1alpha1.Payload, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Payload, error)
	List(opts v1.ListOptions) (*v1alpha1.PayloadList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Payload, err error)
	PayloadExpansion
}

// payloads implements PayloadInterface
type payloads struct {
	client rest.Interface
	ns     string
}

// newPayloads returns a Payloads
func newPayloads(c *ReleaseV1alpha1Client, namespace string) *payloads {
	return &payloads{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the payload, and returns the corresponding payload object, and an error if there is any.
func (c *payloads) Get(name string, options v1.GetOptions) (result *v1alpha1.Payload, err error) {
	result = &v1alpha1.Payload{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("payloads").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Payloads that match those selectors.
func (c *payloads) List(opts v1.ListOptions) (result *v1alpha1.PayloadList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PayloadList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("payloads").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested payloads.
func (c *payloads) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("payloads").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a payload and creates it.  Returns the server's representation of the payload, and an error, if there is any.
func (c *payloads) Create(payload *v1alpha1.Payload) (result *v1alpha1.Payload, err error) {
	result = &v1alpha1.Payload{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("payloads").
		Body(payload).
		Do().
		Into(result)
	return
}

// Update takes the representation of a payload and updates it. Returns the server's representation of the payload, and an error, if there is any.
func (c *payloads) Update(payload *v1alpha1.Payload) (result *v1alpha1.Payload, err error) {
	result = &v1alpha1.Payload{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("payloads").
		Name(payload.Name).
		Body(payload).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *payloads) UpdateStatus(payload *v1alpha1.Payload) (result *v1alpha1.Payload, err error) {
	result = &v1alpha1.Payload{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("payloads").
		Name(payload.Name).
		SubResource("status").
		Body(payload).
		Do().
		Into(result)
	return
}

// Delete takes name of the payload and deletes it. Returns an error if one occurs.
func (c *payloads) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("payloads").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *payloads) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("payloads").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched payload.
func (c *payloads) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Payload, err error) {
	result = &v1alpha1.Payload{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("payloads").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
