/*
Copyright 2020 The OpenShift Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	releasev1alpha1 "github.com/vfreex/release-apiserver/pkg/apis/release/v1alpha1"
	clientset "github.com/vfreex/release-apiserver/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/vfreex/release-apiserver/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/vfreex/release-apiserver/pkg/client/listers_generated/release/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PayloadInformer provides access to a shared informer and lister for
// Payloads.
type PayloadInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PayloadLister
}

type payloadInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPayloadInformer constructs a new informer for Payload type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPayloadInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPayloadInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPayloadInformer constructs a new informer for Payload type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPayloadInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ReleaseV1alpha1().Payloads(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ReleaseV1alpha1().Payloads(namespace).Watch(options)
			},
		},
		&releasev1alpha1.Payload{},
		resyncPeriod,
		indexers,
	)
}

func (f *payloadInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPayloadInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *payloadInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&releasev1alpha1.Payload{}, f.defaultInformer)
}

func (f *payloadInformer) Lister() v1alpha1.PayloadLister {
	return v1alpha1.NewPayloadLister(f.Informer().GetIndexer())
}
