/*
Copyright 2020 The OpenShift Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	releasev1alpha1 "github.com/vfreex/release-apiserver/pkg/apis/release/v1alpha1"
	clientset "github.com/vfreex/release-apiserver/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/vfreex/release-apiserver/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/vfreex/release-apiserver/pkg/client/listers_generated/release/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SourceRevisionInformer provides access to a shared informer and lister for
// SourceRevisions.
type SourceRevisionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SourceRevisionLister
}

type sourceRevisionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSourceRevisionInformer constructs a new informer for SourceRevision type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSourceRevisionInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSourceRevisionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSourceRevisionInformer constructs a new informer for SourceRevision type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSourceRevisionInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ReleaseV1alpha1().SourceRevisions(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ReleaseV1alpha1().SourceRevisions(namespace).Watch(options)
			},
		},
		&releasev1alpha1.SourceRevision{},
		resyncPeriod,
		indexers,
	)
}

func (f *sourceRevisionInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSourceRevisionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *sourceRevisionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&releasev1alpha1.SourceRevision{}, f.defaultInformer)
}

func (f *sourceRevisionInformer) Lister() v1alpha1.SourceRevisionLister {
	return v1alpha1.NewSourceRevisionLister(f.Informer().GetIndexer())
}
