# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openshift_release.configuration import Configuration


class ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisoryStatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'live_id': 'str',
        'state': 'str'
    }

    attribute_map = {
        'live_id': 'liveID',
        'state': 'state'
    }

    def __init__(self, live_id=None, state=None, local_vars_configuration=None):  # noqa: E501
        """ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisoryStatus - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._live_id = None
        self._state = None
        self.discriminator = None

        if live_id is not None:
            self.live_id = live_id
        if state is not None:
            self.state = state

    @property
    def live_id(self):
        """Gets the live_id of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisoryStatus.  # noqa: E501


        :return: The live_id of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisoryStatus.  # noqa: E501
        :rtype: str
        """
        return self._live_id

    @live_id.setter
    def live_id(self, live_id):
        """Sets the live_id of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisoryStatus.


        :param live_id: The live_id of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisoryStatus.  # noqa: E501
        :type: str
        """

        self._live_id = live_id

    @property
    def state(self):
        """Gets the state of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisoryStatus.  # noqa: E501


        :return: The state of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisoryStatus.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisoryStatus.


        :param state: The state of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisoryStatus.  # noqa: E501
        :type: str
        """

        self._state = state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisoryStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisoryStatus):
            return True

        return self.to_dict() != other.to_dict()
