# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openshift_release.configuration import Configuration


class ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ReleaseStreamOcpBuildData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'git': 'ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1OcpBuildDataGitSource'
    }

    attribute_map = {
        'git': 'git'
    }

    def __init__(self, git=None, local_vars_configuration=None):  # noqa: E501
        """ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ReleaseStreamOcpBuildData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._git = None
        self.discriminator = None

        if git is not None:
            self.git = git

    @property
    def git(self):
        """Gets the git of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ReleaseStreamOcpBuildData.  # noqa: E501


        :return: The git of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ReleaseStreamOcpBuildData.  # noqa: E501
        :rtype: ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1OcpBuildDataGitSource
        """
        return self._git

    @git.setter
    def git(self, git):
        """Sets the git of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ReleaseStreamOcpBuildData.


        :param git: The git of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ReleaseStreamOcpBuildData.  # noqa: E501
        :type: ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1OcpBuildDataGitSource
        """

        self._git = git

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ReleaseStreamOcpBuildData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1ReleaseStreamOcpBuildData):
            return True

        return self.to_dict() != other.to_dict()
