# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openshift_release.configuration import Configuration


class ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'impetus': 'str',
        'instance': 'str',
        'number': 'int',
        'release_name': 'str'
    }

    attribute_map = {
        'impetus': 'impetus',
        'instance': 'instance',
        'number': 'number',
        'release_name': 'releaseName'
    }

    def __init__(self, impetus=None, instance=None, number=None, release_name=None, local_vars_configuration=None):  # noqa: E501
        """ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._impetus = None
        self._instance = None
        self._number = None
        self._release_name = None
        self.discriminator = None

        if impetus is not None:
            self.impetus = impetus
        if instance is not None:
            self.instance = instance
        if number is not None:
            self.number = number
        if release_name is not None:
            self.release_name = release_name

    @property
    def impetus(self):
        """Gets the impetus of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec.  # noqa: E501


        :return: The impetus of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec.  # noqa: E501
        :rtype: str
        """
        return self._impetus

    @impetus.setter
    def impetus(self, impetus):
        """Sets the impetus of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec.


        :param impetus: The impetus of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec.  # noqa: E501
        :type: str
        """

        self._impetus = impetus

    @property
    def instance(self):
        """Gets the instance of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec.  # noqa: E501


        :return: The instance of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec.  # noqa: E501
        :rtype: str
        """
        return self._instance

    @instance.setter
    def instance(self, instance):
        """Sets the instance of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec.


        :param instance: The instance of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec.  # noqa: E501
        :type: str
        """

        self._instance = instance

    @property
    def number(self):
        """Gets the number of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec.  # noqa: E501


        :return: The number of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec.  # noqa: E501
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec.


        :param number: The number of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec.  # noqa: E501
        :type: int
        """

        self._number = number

    @property
    def release_name(self):
        """Gets the release_name of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec.  # noqa: E501


        :return: The release_name of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec.  # noqa: E501
        :rtype: str
        """
        return self._release_name

    @release_name.setter
    def release_name(self, release_name):
        """Sets the release_name of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec.


        :param release_name: The release_name of this ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec.  # noqa: E501
        :type: str
        """

        self._release_name = release_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ComGithubVfreexReleaseApiserverPkgApisArtV1alpha1AdvisorySpec):
            return True

        return self.to_dict() != other.to_dict()
