/*
Copyright 2020 The OpenShift Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AdvisoryListerExpansion allows custom methods to be added to
// AdvisoryLister.
type AdvisoryListerExpansion interface{}

// AdvisoryNamespaceListerExpansion allows custom methods to be added to
// AdvisoryNamespaceLister.
type AdvisoryNamespaceListerExpansion interface{}

// BuildListerExpansion allows custom methods to be added to
// BuildLister.
type BuildListerExpansion interface{}

// BuildNamespaceListerExpansion allows custom methods to be added to
// BuildNamespaceLister.
type BuildNamespaceListerExpansion interface{}

// ComponentListerExpansion allows custom methods to be added to
// ComponentLister.
type ComponentListerExpansion interface{}

// ComponentNamespaceListerExpansion allows custom methods to be added to
// ComponentNamespaceLister.
type ComponentNamespaceListerExpansion interface{}

// RPMComposeListerExpansion allows custom methods to be added to
// RPMComposeLister.
type RPMComposeListerExpansion interface{}

// RPMComposeNamespaceListerExpansion allows custom methods to be added to
// RPMComposeNamespaceLister.
type RPMComposeNamespaceListerExpansion interface{}

// ReleaseListerExpansion allows custom methods to be added to
// ReleaseLister.
type ReleaseListerExpansion interface{}

// ReleaseNamespaceListerExpansion allows custom methods to be added to
// ReleaseNamespaceLister.
type ReleaseNamespaceListerExpansion interface{}

// ReleaseStreamListerExpansion allows custom methods to be added to
// ReleaseStreamLister.
type ReleaseStreamListerExpansion interface{}

// ReleaseStreamNamespaceListerExpansion allows custom methods to be added to
// ReleaseStreamNamespaceLister.
type ReleaseStreamNamespaceListerExpansion interface{}

// SourceRevisionListerExpansion allows custom methods to be added to
// SourceRevisionLister.
type SourceRevisionListerExpansion interface{}

// SourceRevisionNamespaceListerExpansion allows custom methods to be added to
// SourceRevisionNamespaceLister.
type SourceRevisionNamespaceListerExpansion interface{}
