// +build !ignore_autogenerated

/*
Copyright 2020 The OCP Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	proxy "github.com/vfreex/release-apiserver/pkg/apis/proxy"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*KojiImageBuild)(nil), (*proxy.KojiImageBuild)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KojiImageBuild_To_proxy_KojiImageBuild(a.(*KojiImageBuild), b.(*proxy.KojiImageBuild), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*proxy.KojiImageBuild)(nil), (*KojiImageBuild)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_proxy_KojiImageBuild_To_v1alpha1_KojiImageBuild(a.(*proxy.KojiImageBuild), b.(*KojiImageBuild), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KojiImageBuildList)(nil), (*proxy.KojiImageBuildList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KojiImageBuildList_To_proxy_KojiImageBuildList(a.(*KojiImageBuildList), b.(*proxy.KojiImageBuildList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*proxy.KojiImageBuildList)(nil), (*KojiImageBuildList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_proxy_KojiImageBuildList_To_v1alpha1_KojiImageBuildList(a.(*proxy.KojiImageBuildList), b.(*KojiImageBuildList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KojiImageBuildSpec)(nil), (*proxy.KojiImageBuildSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KojiImageBuildSpec_To_proxy_KojiImageBuildSpec(a.(*KojiImageBuildSpec), b.(*proxy.KojiImageBuildSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*proxy.KojiImageBuildSpec)(nil), (*KojiImageBuildSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_proxy_KojiImageBuildSpec_To_v1alpha1_KojiImageBuildSpec(a.(*proxy.KojiImageBuildSpec), b.(*KojiImageBuildSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KojiImageBuildStatus)(nil), (*proxy.KojiImageBuildStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KojiImageBuildStatus_To_proxy_KojiImageBuildStatus(a.(*KojiImageBuildStatus), b.(*proxy.KojiImageBuildStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*proxy.KojiImageBuildStatus)(nil), (*KojiImageBuildStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_proxy_KojiImageBuildStatus_To_v1alpha1_KojiImageBuildStatus(a.(*proxy.KojiImageBuildStatus), b.(*KojiImageBuildStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_KojiImageBuild_To_proxy_KojiImageBuild(in *KojiImageBuild, out *proxy.KojiImageBuild, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_KojiImageBuildSpec_To_proxy_KojiImageBuildSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_KojiImageBuildStatus_To_proxy_KojiImageBuildStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_KojiImageBuild_To_proxy_KojiImageBuild is an autogenerated conversion function.
func Convert_v1alpha1_KojiImageBuild_To_proxy_KojiImageBuild(in *KojiImageBuild, out *proxy.KojiImageBuild, s conversion.Scope) error {
	return autoConvert_v1alpha1_KojiImageBuild_To_proxy_KojiImageBuild(in, out, s)
}

func autoConvert_proxy_KojiImageBuild_To_v1alpha1_KojiImageBuild(in *proxy.KojiImageBuild, out *KojiImageBuild, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_proxy_KojiImageBuildSpec_To_v1alpha1_KojiImageBuildSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_proxy_KojiImageBuildStatus_To_v1alpha1_KojiImageBuildStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_proxy_KojiImageBuild_To_v1alpha1_KojiImageBuild is an autogenerated conversion function.
func Convert_proxy_KojiImageBuild_To_v1alpha1_KojiImageBuild(in *proxy.KojiImageBuild, out *KojiImageBuild, s conversion.Scope) error {
	return autoConvert_proxy_KojiImageBuild_To_v1alpha1_KojiImageBuild(in, out, s)
}

func autoConvert_v1alpha1_KojiImageBuildList_To_proxy_KojiImageBuildList(in *KojiImageBuildList, out *proxy.KojiImageBuildList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]proxy.KojiImageBuild)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_KojiImageBuildList_To_proxy_KojiImageBuildList is an autogenerated conversion function.
func Convert_v1alpha1_KojiImageBuildList_To_proxy_KojiImageBuildList(in *KojiImageBuildList, out *proxy.KojiImageBuildList, s conversion.Scope) error {
	return autoConvert_v1alpha1_KojiImageBuildList_To_proxy_KojiImageBuildList(in, out, s)
}

func autoConvert_proxy_KojiImageBuildList_To_v1alpha1_KojiImageBuildList(in *proxy.KojiImageBuildList, out *KojiImageBuildList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]KojiImageBuild)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_proxy_KojiImageBuildList_To_v1alpha1_KojiImageBuildList is an autogenerated conversion function.
func Convert_proxy_KojiImageBuildList_To_v1alpha1_KojiImageBuildList(in *proxy.KojiImageBuildList, out *KojiImageBuildList, s conversion.Scope) error {
	return autoConvert_proxy_KojiImageBuildList_To_v1alpha1_KojiImageBuildList(in, out, s)
}

func autoConvert_v1alpha1_KojiImageBuildSpec_To_proxy_KojiImageBuildSpec(in *KojiImageBuildSpec, out *proxy.KojiImageBuildSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.Release = in.Release
	return nil
}

// Convert_v1alpha1_KojiImageBuildSpec_To_proxy_KojiImageBuildSpec is an autogenerated conversion function.
func Convert_v1alpha1_KojiImageBuildSpec_To_proxy_KojiImageBuildSpec(in *KojiImageBuildSpec, out *proxy.KojiImageBuildSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_KojiImageBuildSpec_To_proxy_KojiImageBuildSpec(in, out, s)
}

func autoConvert_proxy_KojiImageBuildSpec_To_v1alpha1_KojiImageBuildSpec(in *proxy.KojiImageBuildSpec, out *KojiImageBuildSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.Release = in.Release
	return nil
}

// Convert_proxy_KojiImageBuildSpec_To_v1alpha1_KojiImageBuildSpec is an autogenerated conversion function.
func Convert_proxy_KojiImageBuildSpec_To_v1alpha1_KojiImageBuildSpec(in *proxy.KojiImageBuildSpec, out *KojiImageBuildSpec, s conversion.Scope) error {
	return autoConvert_proxy_KojiImageBuildSpec_To_v1alpha1_KojiImageBuildSpec(in, out, s)
}

func autoConvert_v1alpha1_KojiImageBuildStatus_To_proxy_KojiImageBuildStatus(in *KojiImageBuildStatus, out *proxy.KojiImageBuildStatus, s conversion.Scope) error {
	out.KojiState = in.KojiState
	out.KojiBuildLink = in.KojiBuildLink
	return nil
}

// Convert_v1alpha1_KojiImageBuildStatus_To_proxy_KojiImageBuildStatus is an autogenerated conversion function.
func Convert_v1alpha1_KojiImageBuildStatus_To_proxy_KojiImageBuildStatus(in *KojiImageBuildStatus, out *proxy.KojiImageBuildStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_KojiImageBuildStatus_To_proxy_KojiImageBuildStatus(in, out, s)
}

func autoConvert_proxy_KojiImageBuildStatus_To_v1alpha1_KojiImageBuildStatus(in *proxy.KojiImageBuildStatus, out *KojiImageBuildStatus, s conversion.Scope) error {
	out.KojiState = in.KojiState
	out.KojiBuildLink = in.KojiBuildLink
	return nil
}

// Convert_proxy_KojiImageBuildStatus_To_v1alpha1_KojiImageBuildStatus is an autogenerated conversion function.
func Convert_proxy_KojiImageBuildStatus_To_v1alpha1_KojiImageBuildStatus(in *proxy.KojiImageBuildStatus, out *KojiImageBuildStatus, s conversion.Scope) error {
	return autoConvert_proxy_KojiImageBuildStatus_To_v1alpha1_KojiImageBuildStatus(in, out, s)
}
