/*
Copyright 2020 The OCP Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/vfreex/release-apiserver/pkg/apis/proxy/v1alpha1"
	scheme "github.com/vfreex/release-apiserver/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KojiImageBuildPackagesGetter has a method to return a KojiImageBuildPackageInterface.
// A group's client should implement this interface.
type KojiImageBuildPackagesGetter interface {
	KojiImageBuildPackages(namespace string) KojiImageBuildPackageInterface
}

// KojiImageBuildPackageInterface has methods to work with KojiImageBuildPackage resources.
type KojiImageBuildPackageInterface interface {
	Create(*v1alpha1.KojiImageBuildPackage) (*v1alpha1.KojiImageBuildPackage, error)
	Update(*v1alpha1.KojiImageBuildPackage) (*v1alpha1.KojiImageBuildPackage, error)
	UpdateStatus(*v1alpha1.KojiImageBuildPackage) (*v1alpha1.KojiImageBuildPackage, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.KojiImageBuildPackage, error)
	List(opts v1.ListOptions) (*v1alpha1.KojiImageBuildPackageList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KojiImageBuildPackage, err error)
	KojiImageBuildPackageExpansion
}

// kojiImageBuildPackages implements KojiImageBuildPackageInterface
type kojiImageBuildPackages struct {
	client rest.Interface
	ns     string
}

// newKojiImageBuildPackages returns a KojiImageBuildPackages
func newKojiImageBuildPackages(c *ProxyV1alpha1Client, namespace string) *kojiImageBuildPackages {
	return &kojiImageBuildPackages{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kojiImageBuildPackage, and returns the corresponding kojiImageBuildPackage object, and an error if there is any.
func (c *kojiImageBuildPackages) Get(name string, options v1.GetOptions) (result *v1alpha1.KojiImageBuildPackage, err error) {
	result = &v1alpha1.KojiImageBuildPackage{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kojiimagebuildpackages").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KojiImageBuildPackages that match those selectors.
func (c *kojiImageBuildPackages) List(opts v1.ListOptions) (result *v1alpha1.KojiImageBuildPackageList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KojiImageBuildPackageList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kojiimagebuildpackages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kojiImageBuildPackages.
func (c *kojiImageBuildPackages) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kojiimagebuildpackages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a kojiImageBuildPackage and creates it.  Returns the server's representation of the kojiImageBuildPackage, and an error, if there is any.
func (c *kojiImageBuildPackages) Create(kojiImageBuildPackage *v1alpha1.KojiImageBuildPackage) (result *v1alpha1.KojiImageBuildPackage, err error) {
	result = &v1alpha1.KojiImageBuildPackage{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kojiimagebuildpackages").
		Body(kojiImageBuildPackage).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kojiImageBuildPackage and updates it. Returns the server's representation of the kojiImageBuildPackage, and an error, if there is any.
func (c *kojiImageBuildPackages) Update(kojiImageBuildPackage *v1alpha1.KojiImageBuildPackage) (result *v1alpha1.KojiImageBuildPackage, err error) {
	result = &v1alpha1.KojiImageBuildPackage{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kojiimagebuildpackages").
		Name(kojiImageBuildPackage.Name).
		Body(kojiImageBuildPackage).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *kojiImageBuildPackages) UpdateStatus(kojiImageBuildPackage *v1alpha1.KojiImageBuildPackage) (result *v1alpha1.KojiImageBuildPackage, err error) {
	result = &v1alpha1.KojiImageBuildPackage{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kojiimagebuildpackages").
		Name(kojiImageBuildPackage.Name).
		SubResource("status").
		Body(kojiImageBuildPackage).
		Do().
		Into(result)
	return
}

// Delete takes name of the kojiImageBuildPackage and deletes it. Returns an error if one occurs.
func (c *kojiImageBuildPackages) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kojiimagebuildpackages").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kojiImageBuildPackages) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kojiimagebuildpackages").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kojiImageBuildPackage.
func (c *kojiImageBuildPackages) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KojiImageBuildPackage, err error) {
	result = &v1alpha1.KojiImageBuildPackage{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kojiimagebuildpackages").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
