/*
Copyright 2020 The OpenShift Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/vfreex/release-apiserver/pkg/apis/art/v1alpha1"
	scheme "github.com/vfreex/release-apiserver/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ReleaseStreamsGetter has a method to return a ReleaseStreamInterface.
// A group's client should implement this interface.
type ReleaseStreamsGetter interface {
	ReleaseStreams(namespace string) ReleaseStreamInterface
}

// ReleaseStreamInterface has methods to work with ReleaseStream resources.
type ReleaseStreamInterface interface {
	Create(*v1alpha1.ReleaseStream) (*v1alpha1.ReleaseStream, error)
	Update(*v1alpha1.ReleaseStream) (*v1alpha1.ReleaseStream, error)
	UpdateStatus(*v1alpha1.ReleaseStream) (*v1alpha1.ReleaseStream, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ReleaseStream, error)
	List(opts v1.ListOptions) (*v1alpha1.ReleaseStreamList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ReleaseStream, err error)
	ReleaseStreamExpansion
}

// releaseStreams implements ReleaseStreamInterface
type releaseStreams struct {
	client rest.Interface
	ns     string
}

// newReleaseStreams returns a ReleaseStreams
func newReleaseStreams(c *ArtV1alpha1Client, namespace string) *releaseStreams {
	return &releaseStreams{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the releaseStream, and returns the corresponding releaseStream object, and an error if there is any.
func (c *releaseStreams) Get(name string, options v1.GetOptions) (result *v1alpha1.ReleaseStream, err error) {
	result = &v1alpha1.ReleaseStream{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("releasestreams").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ReleaseStreams that match those selectors.
func (c *releaseStreams) List(opts v1.ListOptions) (result *v1alpha1.ReleaseStreamList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ReleaseStreamList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("releasestreams").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested releaseStreams.
func (c *releaseStreams) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("releasestreams").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a releaseStream and creates it.  Returns the server's representation of the releaseStream, and an error, if there is any.
func (c *releaseStreams) Create(releaseStream *v1alpha1.ReleaseStream) (result *v1alpha1.ReleaseStream, err error) {
	result = &v1alpha1.ReleaseStream{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("releasestreams").
		Body(releaseStream).
		Do().
		Into(result)
	return
}

// Update takes the representation of a releaseStream and updates it. Returns the server's representation of the releaseStream, and an error, if there is any.
func (c *releaseStreams) Update(releaseStream *v1alpha1.ReleaseStream) (result *v1alpha1.ReleaseStream, err error) {
	result = &v1alpha1.ReleaseStream{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("releasestreams").
		Name(releaseStream.Name).
		Body(releaseStream).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *releaseStreams) UpdateStatus(releaseStream *v1alpha1.ReleaseStream) (result *v1alpha1.ReleaseStream, err error) {
	result = &v1alpha1.ReleaseStream{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("releasestreams").
		Name(releaseStream.Name).
		SubResource("status").
		Body(releaseStream).
		Do().
		Into(result)
	return
}

// Delete takes name of the releaseStream and deletes it. Returns an error if one occurs.
func (c *releaseStreams) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("releasestreams").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *releaseStreams) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("releasestreams").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched releaseStream.
func (c *releaseStreams) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ReleaseStream, err error) {
	result = &v1alpha1.ReleaseStream{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("releasestreams").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
