/*
Copyright 2020 The OpenShift Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/vfreex/release-apiserver/pkg/apis/art/v1alpha1"
	scheme "github.com/vfreex/release-apiserver/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RPMComposesGetter has a method to return a RPMComposeInterface.
// A group's client should implement this interface.
type RPMComposesGetter interface {
	RPMComposes(namespace string) RPMComposeInterface
}

// RPMComposeInterface has methods to work with RPMCompose resources.
type RPMComposeInterface interface {
	Create(*v1alpha1.RPMCompose) (*v1alpha1.RPMCompose, error)
	Update(*v1alpha1.RPMCompose) (*v1alpha1.RPMCompose, error)
	UpdateStatus(*v1alpha1.RPMCompose) (*v1alpha1.RPMCompose, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.RPMCompose, error)
	List(opts v1.ListOptions) (*v1alpha1.RPMComposeList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RPMCompose, err error)
	RPMComposeExpansion
}

// rPMComposes implements RPMComposeInterface
type rPMComposes struct {
	client rest.Interface
	ns     string
}

// newRPMComposes returns a RPMComposes
func newRPMComposes(c *ArtV1alpha1Client, namespace string) *rPMComposes {
	return &rPMComposes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rPMCompose, and returns the corresponding rPMCompose object, and an error if there is any.
func (c *rPMComposes) Get(name string, options v1.GetOptions) (result *v1alpha1.RPMCompose, err error) {
	result = &v1alpha1.RPMCompose{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rpmcomposes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RPMComposes that match those selectors.
func (c *rPMComposes) List(opts v1.ListOptions) (result *v1alpha1.RPMComposeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RPMComposeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rpmcomposes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rPMComposes.
func (c *rPMComposes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rpmcomposes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a rPMCompose and creates it.  Returns the server's representation of the rPMCompose, and an error, if there is any.
func (c *rPMComposes) Create(rPMCompose *v1alpha1.RPMCompose) (result *v1alpha1.RPMCompose, err error) {
	result = &v1alpha1.RPMCompose{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rpmcomposes").
		Body(rPMCompose).
		Do().
		Into(result)
	return
}

// Update takes the representation of a rPMCompose and updates it. Returns the server's representation of the rPMCompose, and an error, if there is any.
func (c *rPMComposes) Update(rPMCompose *v1alpha1.RPMCompose) (result *v1alpha1.RPMCompose, err error) {
	result = &v1alpha1.RPMCompose{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rpmcomposes").
		Name(rPMCompose.Name).
		Body(rPMCompose).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *rPMComposes) UpdateStatus(rPMCompose *v1alpha1.RPMCompose) (result *v1alpha1.RPMCompose, err error) {
	result = &v1alpha1.RPMCompose{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rpmcomposes").
		Name(rPMCompose.Name).
		SubResource("status").
		Body(rPMCompose).
		Do().
		Into(result)
	return
}

// Delete takes name of the rPMCompose and deletes it. Returns an error if one occurs.
func (c *rPMComposes) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rpmcomposes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rPMComposes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rpmcomposes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched rPMCompose.
func (c *rPMComposes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RPMCompose, err error) {
	result = &v1alpha1.RPMCompose{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rpmcomposes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
