/*
Copyright 2020 The OpenShift Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/vfreex/release-apiserver/pkg/apis/art/v1alpha1"
	scheme "github.com/vfreex/release-apiserver/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SourceRevisionsGetter has a method to return a SourceRevisionInterface.
// A group's client should implement this interface.
type SourceRevisionsGetter interface {
	SourceRevisions(namespace string) SourceRevisionInterface
}

// SourceRevisionInterface has methods to work with SourceRevision resources.
type SourceRevisionInterface interface {
	Create(*v1alpha1.SourceRevision) (*v1alpha1.SourceRevision, error)
	Update(*v1alpha1.SourceRevision) (*v1alpha1.SourceRevision, error)
	UpdateStatus(*v1alpha1.SourceRevision) (*v1alpha1.SourceRevision, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SourceRevision, error)
	List(opts v1.ListOptions) (*v1alpha1.SourceRevisionList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SourceRevision, err error)
	SourceRevisionExpansion
}

// sourceRevisions implements SourceRevisionInterface
type sourceRevisions struct {
	client rest.Interface
	ns     string
}

// newSourceRevisions returns a SourceRevisions
func newSourceRevisions(c *ArtV1alpha1Client, namespace string) *sourceRevisions {
	return &sourceRevisions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sourceRevision, and returns the corresponding sourceRevision object, and an error if there is any.
func (c *sourceRevisions) Get(name string, options v1.GetOptions) (result *v1alpha1.SourceRevision, err error) {
	result = &v1alpha1.SourceRevision{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sourcerevisions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SourceRevisions that match those selectors.
func (c *sourceRevisions) List(opts v1.ListOptions) (result *v1alpha1.SourceRevisionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SourceRevisionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sourcerevisions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sourceRevisions.
func (c *sourceRevisions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sourcerevisions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a sourceRevision and creates it.  Returns the server's representation of the sourceRevision, and an error, if there is any.
func (c *sourceRevisions) Create(sourceRevision *v1alpha1.SourceRevision) (result *v1alpha1.SourceRevision, err error) {
	result = &v1alpha1.SourceRevision{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sourcerevisions").
		Body(sourceRevision).
		Do().
		Into(result)
	return
}

// Update takes the representation of a sourceRevision and updates it. Returns the server's representation of the sourceRevision, and an error, if there is any.
func (c *sourceRevisions) Update(sourceRevision *v1alpha1.SourceRevision) (result *v1alpha1.SourceRevision, err error) {
	result = &v1alpha1.SourceRevision{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sourcerevisions").
		Name(sourceRevision.Name).
		Body(sourceRevision).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *sourceRevisions) UpdateStatus(sourceRevision *v1alpha1.SourceRevision) (result *v1alpha1.SourceRevision, err error) {
	result = &v1alpha1.SourceRevision{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sourcerevisions").
		Name(sourceRevision.Name).
		SubResource("status").
		Body(sourceRevision).
		Do().
		Into(result)
	return
}

// Delete takes name of the sourceRevision and deletes it. Returns an error if one occurs.
func (c *sourceRevisions) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sourcerevisions").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sourceRevisions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sourcerevisions").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched sourceRevision.
func (c *sourceRevisions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SourceRevision, err error) {
	result = &v1alpha1.SourceRevision{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sourcerevisions").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
