// +build !ignore_autogenerated

/*
Copyright 2020 The OpenShift Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	art "github.com/vfreex/release-apiserver/pkg/apis/art"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Advisory)(nil), (*art.Advisory)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Advisory_To_art_Advisory(a.(*Advisory), b.(*art.Advisory), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.Advisory)(nil), (*Advisory)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_Advisory_To_v1alpha1_Advisory(a.(*art.Advisory), b.(*Advisory), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AdvisoryList)(nil), (*art.AdvisoryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AdvisoryList_To_art_AdvisoryList(a.(*AdvisoryList), b.(*art.AdvisoryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.AdvisoryList)(nil), (*AdvisoryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_AdvisoryList_To_v1alpha1_AdvisoryList(a.(*art.AdvisoryList), b.(*AdvisoryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AdvisorySpec)(nil), (*art.AdvisorySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AdvisorySpec_To_art_AdvisorySpec(a.(*AdvisorySpec), b.(*art.AdvisorySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.AdvisorySpec)(nil), (*AdvisorySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_AdvisorySpec_To_v1alpha1_AdvisorySpec(a.(*art.AdvisorySpec), b.(*AdvisorySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AdvisoryStatus)(nil), (*art.AdvisoryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AdvisoryStatus_To_art_AdvisoryStatus(a.(*AdvisoryStatus), b.(*art.AdvisoryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.AdvisoryStatus)(nil), (*AdvisoryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_AdvisoryStatus_To_v1alpha1_AdvisoryStatus(a.(*art.AdvisoryStatus), b.(*AdvisoryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BrewBuild)(nil), (*art.BrewBuild)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BrewBuild_To_art_BrewBuild(a.(*BrewBuild), b.(*art.BrewBuild), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.BrewBuild)(nil), (*BrewBuild)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_BrewBuild_To_v1alpha1_BrewBuild(a.(*art.BrewBuild), b.(*BrewBuild), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Build)(nil), (*art.Build)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Build_To_art_Build(a.(*Build), b.(*art.Build), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.Build)(nil), (*Build)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_Build_To_v1alpha1_Build(a.(*art.Build), b.(*Build), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BuildJenkinsInfo)(nil), (*art.BuildJenkinsInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BuildJenkinsInfo_To_art_BuildJenkinsInfo(a.(*BuildJenkinsInfo), b.(*art.BuildJenkinsInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.BuildJenkinsInfo)(nil), (*BuildJenkinsInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_BuildJenkinsInfo_To_v1alpha1_BuildJenkinsInfo(a.(*art.BuildJenkinsInfo), b.(*BuildJenkinsInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BuildList)(nil), (*art.BuildList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BuildList_To_art_BuildList(a.(*BuildList), b.(*art.BuildList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.BuildList)(nil), (*BuildList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_BuildList_To_v1alpha1_BuildList(a.(*art.BuildList), b.(*BuildList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BuildSpec)(nil), (*art.BuildSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BuildSpec_To_art_BuildSpec(a.(*BuildSpec), b.(*art.BuildSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.BuildSpec)(nil), (*BuildSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_BuildSpec_To_v1alpha1_BuildSpec(a.(*art.BuildSpec), b.(*BuildSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BuildStatus)(nil), (*art.BuildStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BuildStatus_To_art_BuildStatus(a.(*BuildStatus), b.(*art.BuildStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.BuildStatus)(nil), (*BuildStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_BuildStatus_To_v1alpha1_BuildStatus(a.(*art.BuildStatus), b.(*BuildStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Component)(nil), (*art.Component)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Component_To_art_Component(a.(*Component), b.(*art.Component), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.Component)(nil), (*Component)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_Component_To_v1alpha1_Component(a.(*art.Component), b.(*Component), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentDistGit)(nil), (*art.ComponentDistGit)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentDistGit_To_art_ComponentDistGit(a.(*ComponentDistGit), b.(*art.ComponentDistGit), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.ComponentDistGit)(nil), (*ComponentDistGit)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_ComponentDistGit_To_v1alpha1_ComponentDistGit(a.(*art.ComponentDistGit), b.(*ComponentDistGit), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentGitSource)(nil), (*art.ComponentGitSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentGitSource_To_art_ComponentGitSource(a.(*ComponentGitSource), b.(*art.ComponentGitSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.ComponentGitSource)(nil), (*ComponentGitSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_ComponentGitSource_To_v1alpha1_ComponentGitSource(a.(*art.ComponentGitSource), b.(*ComponentGitSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentImage)(nil), (*art.ComponentImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentImage_To_art_ComponentImage(a.(*ComponentImage), b.(*art.ComponentImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.ComponentImage)(nil), (*ComponentImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_ComponentImage_To_v1alpha1_ComponentImage(a.(*art.ComponentImage), b.(*ComponentImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentList)(nil), (*art.ComponentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentList_To_art_ComponentList(a.(*ComponentList), b.(*art.ComponentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.ComponentList)(nil), (*ComponentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_ComponentList_To_v1alpha1_ComponentList(a.(*art.ComponentList), b.(*ComponentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentSource)(nil), (*art.ComponentSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentSource_To_art_ComponentSource(a.(*ComponentSource), b.(*art.ComponentSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.ComponentSource)(nil), (*ComponentSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_ComponentSource_To_v1alpha1_ComponentSource(a.(*art.ComponentSource), b.(*ComponentSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentSpec)(nil), (*art.ComponentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentSpec_To_art_ComponentSpec(a.(*ComponentSpec), b.(*art.ComponentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.ComponentSpec)(nil), (*ComponentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_ComponentSpec_To_v1alpha1_ComponentSpec(a.(*art.ComponentSpec), b.(*ComponentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentStatus)(nil), (*art.ComponentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentStatus_To_art_ComponentStatus(a.(*ComponentStatus), b.(*art.ComponentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.ComponentStatus)(nil), (*ComponentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_ComponentStatus_To_v1alpha1_ComponentStatus(a.(*art.ComponentStatus), b.(*ComponentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OcpBuildDataGitSource)(nil), (*art.OcpBuildDataGitSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OcpBuildDataGitSource_To_art_OcpBuildDataGitSource(a.(*OcpBuildDataGitSource), b.(*art.OcpBuildDataGitSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.OcpBuildDataGitSource)(nil), (*OcpBuildDataGitSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_OcpBuildDataGitSource_To_v1alpha1_OcpBuildDataGitSource(a.(*art.OcpBuildDataGitSource), b.(*OcpBuildDataGitSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RPMCompose)(nil), (*art.RPMCompose)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RPMCompose_To_art_RPMCompose(a.(*RPMCompose), b.(*art.RPMCompose), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.RPMCompose)(nil), (*RPMCompose)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_RPMCompose_To_v1alpha1_RPMCompose(a.(*art.RPMCompose), b.(*RPMCompose), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RPMComposeList)(nil), (*art.RPMComposeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RPMComposeList_To_art_RPMComposeList(a.(*RPMComposeList), b.(*art.RPMComposeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.RPMComposeList)(nil), (*RPMComposeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_RPMComposeList_To_v1alpha1_RPMComposeList(a.(*art.RPMComposeList), b.(*RPMComposeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RPMComposeSpec)(nil), (*art.RPMComposeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RPMComposeSpec_To_art_RPMComposeSpec(a.(*RPMComposeSpec), b.(*art.RPMComposeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.RPMComposeSpec)(nil), (*RPMComposeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_RPMComposeSpec_To_v1alpha1_RPMComposeSpec(a.(*art.RPMComposeSpec), b.(*RPMComposeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RPMComposeStatus)(nil), (*art.RPMComposeStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RPMComposeStatus_To_art_RPMComposeStatus(a.(*RPMComposeStatus), b.(*art.RPMComposeStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.RPMComposeStatus)(nil), (*RPMComposeStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_RPMComposeStatus_To_v1alpha1_RPMComposeStatus(a.(*art.RPMComposeStatus), b.(*RPMComposeStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Release)(nil), (*art.Release)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Release_To_art_Release(a.(*Release), b.(*art.Release), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.Release)(nil), (*Release)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_Release_To_v1alpha1_Release(a.(*art.Release), b.(*Release), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseList)(nil), (*art.ReleaseList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseList_To_art_ReleaseList(a.(*ReleaseList), b.(*art.ReleaseList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.ReleaseList)(nil), (*ReleaseList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_ReleaseList_To_v1alpha1_ReleaseList(a.(*art.ReleaseList), b.(*ReleaseList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseSpec)(nil), (*art.ReleaseSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseSpec_To_art_ReleaseSpec(a.(*ReleaseSpec), b.(*art.ReleaseSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.ReleaseSpec)(nil), (*ReleaseSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_ReleaseSpec_To_v1alpha1_ReleaseSpec(a.(*art.ReleaseSpec), b.(*ReleaseSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseStatus)(nil), (*art.ReleaseStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseStatus_To_art_ReleaseStatus(a.(*ReleaseStatus), b.(*art.ReleaseStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.ReleaseStatus)(nil), (*ReleaseStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_ReleaseStatus_To_v1alpha1_ReleaseStatus(a.(*art.ReleaseStatus), b.(*ReleaseStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseStream)(nil), (*art.ReleaseStream)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseStream_To_art_ReleaseStream(a.(*ReleaseStream), b.(*art.ReleaseStream), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.ReleaseStream)(nil), (*ReleaseStream)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_ReleaseStream_To_v1alpha1_ReleaseStream(a.(*art.ReleaseStream), b.(*ReleaseStream), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseStreamList)(nil), (*art.ReleaseStreamList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseStreamList_To_art_ReleaseStreamList(a.(*ReleaseStreamList), b.(*art.ReleaseStreamList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.ReleaseStreamList)(nil), (*ReleaseStreamList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_ReleaseStreamList_To_v1alpha1_ReleaseStreamList(a.(*art.ReleaseStreamList), b.(*ReleaseStreamList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseStreamOcpBuildData)(nil), (*art.ReleaseStreamOcpBuildData)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseStreamOcpBuildData_To_art_ReleaseStreamOcpBuildData(a.(*ReleaseStreamOcpBuildData), b.(*art.ReleaseStreamOcpBuildData), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.ReleaseStreamOcpBuildData)(nil), (*ReleaseStreamOcpBuildData)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_ReleaseStreamOcpBuildData_To_v1alpha1_ReleaseStreamOcpBuildData(a.(*art.ReleaseStreamOcpBuildData), b.(*ReleaseStreamOcpBuildData), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseStreamSpec)(nil), (*art.ReleaseStreamSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseStreamSpec_To_art_ReleaseStreamSpec(a.(*ReleaseStreamSpec), b.(*art.ReleaseStreamSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.ReleaseStreamSpec)(nil), (*ReleaseStreamSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_ReleaseStreamSpec_To_v1alpha1_ReleaseStreamSpec(a.(*art.ReleaseStreamSpec), b.(*ReleaseStreamSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseStreamStatus)(nil), (*art.ReleaseStreamStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseStreamStatus_To_art_ReleaseStreamStatus(a.(*ReleaseStreamStatus), b.(*art.ReleaseStreamStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.ReleaseStreamStatus)(nil), (*ReleaseStreamStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_ReleaseStreamStatus_To_v1alpha1_ReleaseStreamStatus(a.(*art.ReleaseStreamStatus), b.(*ReleaseStreamStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseVersion)(nil), (*art.ReleaseVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseVersion_To_art_ReleaseVersion(a.(*ReleaseVersion), b.(*art.ReleaseVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.ReleaseVersion)(nil), (*ReleaseVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_ReleaseVersion_To_v1alpha1_ReleaseVersion(a.(*art.ReleaseVersion), b.(*ReleaseVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SourceRevision)(nil), (*art.SourceRevision)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SourceRevision_To_art_SourceRevision(a.(*SourceRevision), b.(*art.SourceRevision), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.SourceRevision)(nil), (*SourceRevision)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_SourceRevision_To_v1alpha1_SourceRevision(a.(*art.SourceRevision), b.(*SourceRevision), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SourceRevisionList)(nil), (*art.SourceRevisionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SourceRevisionList_To_art_SourceRevisionList(a.(*SourceRevisionList), b.(*art.SourceRevisionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.SourceRevisionList)(nil), (*SourceRevisionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_SourceRevisionList_To_v1alpha1_SourceRevisionList(a.(*art.SourceRevisionList), b.(*SourceRevisionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SourceRevisionSpec)(nil), (*art.SourceRevisionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SourceRevisionSpec_To_art_SourceRevisionSpec(a.(*SourceRevisionSpec), b.(*art.SourceRevisionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.SourceRevisionSpec)(nil), (*SourceRevisionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_SourceRevisionSpec_To_v1alpha1_SourceRevisionSpec(a.(*art.SourceRevisionSpec), b.(*SourceRevisionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SourceRevisionStatus)(nil), (*art.SourceRevisionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SourceRevisionStatus_To_art_SourceRevisionStatus(a.(*SourceRevisionStatus), b.(*art.SourceRevisionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*art.SourceRevisionStatus)(nil), (*SourceRevisionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_art_SourceRevisionStatus_To_v1alpha1_SourceRevisionStatus(a.(*art.SourceRevisionStatus), b.(*SourceRevisionStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Advisory_To_art_Advisory(in *Advisory, out *art.Advisory, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_AdvisorySpec_To_art_AdvisorySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_AdvisoryStatus_To_art_AdvisoryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Advisory_To_art_Advisory is an autogenerated conversion function.
func Convert_v1alpha1_Advisory_To_art_Advisory(in *Advisory, out *art.Advisory, s conversion.Scope) error {
	return autoConvert_v1alpha1_Advisory_To_art_Advisory(in, out, s)
}

func autoConvert_art_Advisory_To_v1alpha1_Advisory(in *art.Advisory, out *Advisory, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_art_AdvisorySpec_To_v1alpha1_AdvisorySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_art_AdvisoryStatus_To_v1alpha1_AdvisoryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_art_Advisory_To_v1alpha1_Advisory is an autogenerated conversion function.
func Convert_art_Advisory_To_v1alpha1_Advisory(in *art.Advisory, out *Advisory, s conversion.Scope) error {
	return autoConvert_art_Advisory_To_v1alpha1_Advisory(in, out, s)
}

func autoConvert_v1alpha1_AdvisoryList_To_art_AdvisoryList(in *AdvisoryList, out *art.AdvisoryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]art.Advisory)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_AdvisoryList_To_art_AdvisoryList is an autogenerated conversion function.
func Convert_v1alpha1_AdvisoryList_To_art_AdvisoryList(in *AdvisoryList, out *art.AdvisoryList, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdvisoryList_To_art_AdvisoryList(in, out, s)
}

func autoConvert_art_AdvisoryList_To_v1alpha1_AdvisoryList(in *art.AdvisoryList, out *AdvisoryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Advisory)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_art_AdvisoryList_To_v1alpha1_AdvisoryList is an autogenerated conversion function.
func Convert_art_AdvisoryList_To_v1alpha1_AdvisoryList(in *art.AdvisoryList, out *AdvisoryList, s conversion.Scope) error {
	return autoConvert_art_AdvisoryList_To_v1alpha1_AdvisoryList(in, out, s)
}

func autoConvert_v1alpha1_AdvisorySpec_To_art_AdvisorySpec(in *AdvisorySpec, out *art.AdvisorySpec, s conversion.Scope) error {
	out.Number = in.Number
	out.Impetus = in.Impetus
	out.ReleaseName = in.ReleaseName
	out.Instance = in.Instance
	return nil
}

// Convert_v1alpha1_AdvisorySpec_To_art_AdvisorySpec is an autogenerated conversion function.
func Convert_v1alpha1_AdvisorySpec_To_art_AdvisorySpec(in *AdvisorySpec, out *art.AdvisorySpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdvisorySpec_To_art_AdvisorySpec(in, out, s)
}

func autoConvert_art_AdvisorySpec_To_v1alpha1_AdvisorySpec(in *art.AdvisorySpec, out *AdvisorySpec, s conversion.Scope) error {
	out.Number = in.Number
	out.Impetus = in.Impetus
	out.ReleaseName = in.ReleaseName
	out.Instance = in.Instance
	return nil
}

// Convert_art_AdvisorySpec_To_v1alpha1_AdvisorySpec is an autogenerated conversion function.
func Convert_art_AdvisorySpec_To_v1alpha1_AdvisorySpec(in *art.AdvisorySpec, out *AdvisorySpec, s conversion.Scope) error {
	return autoConvert_art_AdvisorySpec_To_v1alpha1_AdvisorySpec(in, out, s)
}

func autoConvert_v1alpha1_AdvisoryStatus_To_art_AdvisoryStatus(in *AdvisoryStatus, out *art.AdvisoryStatus, s conversion.Scope) error {
	out.LiveID = in.LiveID
	out.State = in.State
	return nil
}

// Convert_v1alpha1_AdvisoryStatus_To_art_AdvisoryStatus is an autogenerated conversion function.
func Convert_v1alpha1_AdvisoryStatus_To_art_AdvisoryStatus(in *AdvisoryStatus, out *art.AdvisoryStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdvisoryStatus_To_art_AdvisoryStatus(in, out, s)
}

func autoConvert_art_AdvisoryStatus_To_v1alpha1_AdvisoryStatus(in *art.AdvisoryStatus, out *AdvisoryStatus, s conversion.Scope) error {
	out.LiveID = in.LiveID
	out.State = in.State
	return nil
}

// Convert_art_AdvisoryStatus_To_v1alpha1_AdvisoryStatus is an autogenerated conversion function.
func Convert_art_AdvisoryStatus_To_v1alpha1_AdvisoryStatus(in *art.AdvisoryStatus, out *AdvisoryStatus, s conversion.Scope) error {
	return autoConvert_art_AdvisoryStatus_To_v1alpha1_AdvisoryStatus(in, out, s)
}

func autoConvert_v1alpha1_BrewBuild_To_art_BrewBuild(in *BrewBuild, out *art.BrewBuild, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.Release = in.Release
	out.NVR = in.NVR
	out.Target = in.Target
	out.TaskNumber = in.TaskNumber
	out.Instance = in.Instance
	return nil
}

// Convert_v1alpha1_BrewBuild_To_art_BrewBuild is an autogenerated conversion function.
func Convert_v1alpha1_BrewBuild_To_art_BrewBuild(in *BrewBuild, out *art.BrewBuild, s conversion.Scope) error {
	return autoConvert_v1alpha1_BrewBuild_To_art_BrewBuild(in, out, s)
}

func autoConvert_art_BrewBuild_To_v1alpha1_BrewBuild(in *art.BrewBuild, out *BrewBuild, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.Release = in.Release
	out.NVR = in.NVR
	out.Target = in.Target
	out.TaskNumber = in.TaskNumber
	out.Instance = in.Instance
	return nil
}

// Convert_art_BrewBuild_To_v1alpha1_BrewBuild is an autogenerated conversion function.
func Convert_art_BrewBuild_To_v1alpha1_BrewBuild(in *art.BrewBuild, out *BrewBuild, s conversion.Scope) error {
	return autoConvert_art_BrewBuild_To_v1alpha1_BrewBuild(in, out, s)
}

func autoConvert_v1alpha1_Build_To_art_Build(in *Build, out *art.Build, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_BuildSpec_To_art_BuildSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_BuildStatus_To_art_BuildStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Build_To_art_Build is an autogenerated conversion function.
func Convert_v1alpha1_Build_To_art_Build(in *Build, out *art.Build, s conversion.Scope) error {
	return autoConvert_v1alpha1_Build_To_art_Build(in, out, s)
}

func autoConvert_art_Build_To_v1alpha1_Build(in *art.Build, out *Build, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_art_BuildSpec_To_v1alpha1_BuildSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_art_BuildStatus_To_v1alpha1_BuildStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_art_Build_To_v1alpha1_Build is an autogenerated conversion function.
func Convert_art_Build_To_v1alpha1_Build(in *art.Build, out *Build, s conversion.Scope) error {
	return autoConvert_art_Build_To_v1alpha1_Build(in, out, s)
}

func autoConvert_v1alpha1_BuildJenkinsInfo_To_art_BuildJenkinsInfo(in *BuildJenkinsInfo, out *art.BuildJenkinsInfo, s conversion.Scope) error {
	out.BuildUrl = in.BuildUrl
	return nil
}

// Convert_v1alpha1_BuildJenkinsInfo_To_art_BuildJenkinsInfo is an autogenerated conversion function.
func Convert_v1alpha1_BuildJenkinsInfo_To_art_BuildJenkinsInfo(in *BuildJenkinsInfo, out *art.BuildJenkinsInfo, s conversion.Scope) error {
	return autoConvert_v1alpha1_BuildJenkinsInfo_To_art_BuildJenkinsInfo(in, out, s)
}

func autoConvert_art_BuildJenkinsInfo_To_v1alpha1_BuildJenkinsInfo(in *art.BuildJenkinsInfo, out *BuildJenkinsInfo, s conversion.Scope) error {
	out.BuildUrl = in.BuildUrl
	return nil
}

// Convert_art_BuildJenkinsInfo_To_v1alpha1_BuildJenkinsInfo is an autogenerated conversion function.
func Convert_art_BuildJenkinsInfo_To_v1alpha1_BuildJenkinsInfo(in *art.BuildJenkinsInfo, out *BuildJenkinsInfo, s conversion.Scope) error {
	return autoConvert_art_BuildJenkinsInfo_To_v1alpha1_BuildJenkinsInfo(in, out, s)
}

func autoConvert_v1alpha1_BuildList_To_art_BuildList(in *BuildList, out *art.BuildList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]art.Build)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_BuildList_To_art_BuildList is an autogenerated conversion function.
func Convert_v1alpha1_BuildList_To_art_BuildList(in *BuildList, out *art.BuildList, s conversion.Scope) error {
	return autoConvert_v1alpha1_BuildList_To_art_BuildList(in, out, s)
}

func autoConvert_art_BuildList_To_v1alpha1_BuildList(in *art.BuildList, out *BuildList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Build)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_art_BuildList_To_v1alpha1_BuildList is an autogenerated conversion function.
func Convert_art_BuildList_To_v1alpha1_BuildList(in *art.BuildList, out *BuildList, s conversion.Scope) error {
	return autoConvert_art_BuildList_To_v1alpha1_BuildList(in, out, s)
}

func autoConvert_v1alpha1_BuildSpec_To_art_BuildSpec(in *BuildSpec, out *art.BuildSpec, s conversion.Scope) error {
	out.Type = in.Type
	if err := Convert_v1alpha1_BrewBuild_To_art_BrewBuild(&in.Brew, &out.Brew, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_BuildJenkinsInfo_To_art_BuildJenkinsInfo(&in.Jenkins, &out.Jenkins, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BuildSpec_To_art_BuildSpec is an autogenerated conversion function.
func Convert_v1alpha1_BuildSpec_To_art_BuildSpec(in *BuildSpec, out *art.BuildSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_BuildSpec_To_art_BuildSpec(in, out, s)
}

func autoConvert_art_BuildSpec_To_v1alpha1_BuildSpec(in *art.BuildSpec, out *BuildSpec, s conversion.Scope) error {
	out.Type = in.Type
	if err := Convert_art_BrewBuild_To_v1alpha1_BrewBuild(&in.Brew, &out.Brew, s); err != nil {
		return err
	}
	if err := Convert_art_BuildJenkinsInfo_To_v1alpha1_BuildJenkinsInfo(&in.Jenkins, &out.Jenkins, s); err != nil {
		return err
	}
	return nil
}

// Convert_art_BuildSpec_To_v1alpha1_BuildSpec is an autogenerated conversion function.
func Convert_art_BuildSpec_To_v1alpha1_BuildSpec(in *art.BuildSpec, out *BuildSpec, s conversion.Scope) error {
	return autoConvert_art_BuildSpec_To_v1alpha1_BuildSpec(in, out, s)
}

func autoConvert_v1alpha1_BuildStatus_To_art_BuildStatus(in *BuildStatus, out *art.BuildStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_BuildStatus_To_art_BuildStatus is an autogenerated conversion function.
func Convert_v1alpha1_BuildStatus_To_art_BuildStatus(in *BuildStatus, out *art.BuildStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_BuildStatus_To_art_BuildStatus(in, out, s)
}

func autoConvert_art_BuildStatus_To_v1alpha1_BuildStatus(in *art.BuildStatus, out *BuildStatus, s conversion.Scope) error {
	return nil
}

// Convert_art_BuildStatus_To_v1alpha1_BuildStatus is an autogenerated conversion function.
func Convert_art_BuildStatus_To_v1alpha1_BuildStatus(in *art.BuildStatus, out *BuildStatus, s conversion.Scope) error {
	return autoConvert_art_BuildStatus_To_v1alpha1_BuildStatus(in, out, s)
}

func autoConvert_v1alpha1_Component_To_art_Component(in *Component, out *art.Component, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ComponentSpec_To_art_ComponentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ComponentStatus_To_art_ComponentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Component_To_art_Component is an autogenerated conversion function.
func Convert_v1alpha1_Component_To_art_Component(in *Component, out *art.Component, s conversion.Scope) error {
	return autoConvert_v1alpha1_Component_To_art_Component(in, out, s)
}

func autoConvert_art_Component_To_v1alpha1_Component(in *art.Component, out *Component, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_art_ComponentSpec_To_v1alpha1_ComponentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_art_ComponentStatus_To_v1alpha1_ComponentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_art_Component_To_v1alpha1_Component is an autogenerated conversion function.
func Convert_art_Component_To_v1alpha1_Component(in *art.Component, out *Component, s conversion.Scope) error {
	return autoConvert_art_Component_To_v1alpha1_Component(in, out, s)
}

func autoConvert_v1alpha1_ComponentDistGit_To_art_ComponentDistGit(in *ComponentDistGit, out *art.ComponentDistGit, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Repository = in.Repository
	out.Instance = in.Instance
	return nil
}

// Convert_v1alpha1_ComponentDistGit_To_art_ComponentDistGit is an autogenerated conversion function.
func Convert_v1alpha1_ComponentDistGit_To_art_ComponentDistGit(in *ComponentDistGit, out *art.ComponentDistGit, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentDistGit_To_art_ComponentDistGit(in, out, s)
}

func autoConvert_art_ComponentDistGit_To_v1alpha1_ComponentDistGit(in *art.ComponentDistGit, out *ComponentDistGit, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Repository = in.Repository
	out.Instance = in.Instance
	return nil
}

// Convert_art_ComponentDistGit_To_v1alpha1_ComponentDistGit is an autogenerated conversion function.
func Convert_art_ComponentDistGit_To_v1alpha1_ComponentDistGit(in *art.ComponentDistGit, out *ComponentDistGit, s conversion.Scope) error {
	return autoConvert_art_ComponentDistGit_To_v1alpha1_ComponentDistGit(in, out, s)
}

func autoConvert_v1alpha1_ComponentGitSource_To_art_ComponentGitSource(in *ComponentGitSource, out *art.ComponentGitSource, s conversion.Scope) error {
	out.Url = in.Url
	out.Ref = in.Ref
	out.FallbackRef = in.FallbackRef
	out.Path = in.Path
	return nil
}

// Convert_v1alpha1_ComponentGitSource_To_art_ComponentGitSource is an autogenerated conversion function.
func Convert_v1alpha1_ComponentGitSource_To_art_ComponentGitSource(in *ComponentGitSource, out *art.ComponentGitSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentGitSource_To_art_ComponentGitSource(in, out, s)
}

func autoConvert_art_ComponentGitSource_To_v1alpha1_ComponentGitSource(in *art.ComponentGitSource, out *ComponentGitSource, s conversion.Scope) error {
	out.Url = in.Url
	out.Ref = in.Ref
	out.FallbackRef = in.FallbackRef
	out.Path = in.Path
	return nil
}

// Convert_art_ComponentGitSource_To_v1alpha1_ComponentGitSource is an autogenerated conversion function.
func Convert_art_ComponentGitSource_To_v1alpha1_ComponentGitSource(in *art.ComponentGitSource, out *ComponentGitSource, s conversion.Scope) error {
	return autoConvert_art_ComponentGitSource_To_v1alpha1_ComponentGitSource(in, out, s)
}

func autoConvert_v1alpha1_ComponentImage_To_art_ComponentImage(in *ComponentImage, out *art.ComponentImage, s conversion.Scope) error {
	out.Repository = in.Repository
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha1_ComponentImage_To_art_ComponentImage is an autogenerated conversion function.
func Convert_v1alpha1_ComponentImage_To_art_ComponentImage(in *ComponentImage, out *art.ComponentImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentImage_To_art_ComponentImage(in, out, s)
}

func autoConvert_art_ComponentImage_To_v1alpha1_ComponentImage(in *art.ComponentImage, out *ComponentImage, s conversion.Scope) error {
	out.Repository = in.Repository
	out.Namespace = in.Namespace
	return nil
}

// Convert_art_ComponentImage_To_v1alpha1_ComponentImage is an autogenerated conversion function.
func Convert_art_ComponentImage_To_v1alpha1_ComponentImage(in *art.ComponentImage, out *ComponentImage, s conversion.Scope) error {
	return autoConvert_art_ComponentImage_To_v1alpha1_ComponentImage(in, out, s)
}

func autoConvert_v1alpha1_ComponentList_To_art_ComponentList(in *ComponentList, out *art.ComponentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]art.Component)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ComponentList_To_art_ComponentList is an autogenerated conversion function.
func Convert_v1alpha1_ComponentList_To_art_ComponentList(in *ComponentList, out *art.ComponentList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentList_To_art_ComponentList(in, out, s)
}

func autoConvert_art_ComponentList_To_v1alpha1_ComponentList(in *art.ComponentList, out *ComponentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Component)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_art_ComponentList_To_v1alpha1_ComponentList is an autogenerated conversion function.
func Convert_art_ComponentList_To_v1alpha1_ComponentList(in *art.ComponentList, out *ComponentList, s conversion.Scope) error {
	return autoConvert_art_ComponentList_To_v1alpha1_ComponentList(in, out, s)
}

func autoConvert_v1alpha1_ComponentSource_To_art_ComponentSource(in *ComponentSource, out *art.ComponentSource, s conversion.Scope) error {
	if err := Convert_v1alpha1_ComponentGitSource_To_art_ComponentGitSource(&in.Git, &out.Git, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ComponentSource_To_art_ComponentSource is an autogenerated conversion function.
func Convert_v1alpha1_ComponentSource_To_art_ComponentSource(in *ComponentSource, out *art.ComponentSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentSource_To_art_ComponentSource(in, out, s)
}

func autoConvert_art_ComponentSource_To_v1alpha1_ComponentSource(in *art.ComponentSource, out *ComponentSource, s conversion.Scope) error {
	if err := Convert_art_ComponentGitSource_To_v1alpha1_ComponentGitSource(&in.Git, &out.Git, s); err != nil {
		return err
	}
	return nil
}

// Convert_art_ComponentSource_To_v1alpha1_ComponentSource is an autogenerated conversion function.
func Convert_art_ComponentSource_To_v1alpha1_ComponentSource(in *art.ComponentSource, out *ComponentSource, s conversion.Scope) error {
	return autoConvert_art_ComponentSource_To_v1alpha1_ComponentSource(in, out, s)
}

func autoConvert_v1alpha1_ComponentSpec_To_art_ComponentSpec(in *ComponentSpec, out *art.ComponentSpec, s conversion.Scope) error {
	out.Kind = in.Kind
	if err := Convert_v1alpha1_ComponentImage_To_art_ComponentImage(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ComponentSource_To_art_ComponentSource(&in.Source, &out.Source, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ComponentDistGit_To_art_ComponentDistGit(&in.DistGit, &out.DistGit, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ComponentSpec_To_art_ComponentSpec is an autogenerated conversion function.
func Convert_v1alpha1_ComponentSpec_To_art_ComponentSpec(in *ComponentSpec, out *art.ComponentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentSpec_To_art_ComponentSpec(in, out, s)
}

func autoConvert_art_ComponentSpec_To_v1alpha1_ComponentSpec(in *art.ComponentSpec, out *ComponentSpec, s conversion.Scope) error {
	out.Kind = in.Kind
	if err := Convert_art_ComponentImage_To_v1alpha1_ComponentImage(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if err := Convert_art_ComponentSource_To_v1alpha1_ComponentSource(&in.Source, &out.Source, s); err != nil {
		return err
	}
	if err := Convert_art_ComponentDistGit_To_v1alpha1_ComponentDistGit(&in.DistGit, &out.DistGit, s); err != nil {
		return err
	}
	return nil
}

// Convert_art_ComponentSpec_To_v1alpha1_ComponentSpec is an autogenerated conversion function.
func Convert_art_ComponentSpec_To_v1alpha1_ComponentSpec(in *art.ComponentSpec, out *ComponentSpec, s conversion.Scope) error {
	return autoConvert_art_ComponentSpec_To_v1alpha1_ComponentSpec(in, out, s)
}

func autoConvert_v1alpha1_ComponentStatus_To_art_ComponentStatus(in *ComponentStatus, out *art.ComponentStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ComponentStatus_To_art_ComponentStatus is an autogenerated conversion function.
func Convert_v1alpha1_ComponentStatus_To_art_ComponentStatus(in *ComponentStatus, out *art.ComponentStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentStatus_To_art_ComponentStatus(in, out, s)
}

func autoConvert_art_ComponentStatus_To_v1alpha1_ComponentStatus(in *art.ComponentStatus, out *ComponentStatus, s conversion.Scope) error {
	return nil
}

// Convert_art_ComponentStatus_To_v1alpha1_ComponentStatus is an autogenerated conversion function.
func Convert_art_ComponentStatus_To_v1alpha1_ComponentStatus(in *art.ComponentStatus, out *ComponentStatus, s conversion.Scope) error {
	return autoConvert_art_ComponentStatus_To_v1alpha1_ComponentStatus(in, out, s)
}

func autoConvert_v1alpha1_OcpBuildDataGitSource_To_art_OcpBuildDataGitSource(in *OcpBuildDataGitSource, out *art.OcpBuildDataGitSource, s conversion.Scope) error {
	out.Url = in.Url
	out.Ref = in.Ref
	out.Path = in.Path
	return nil
}

// Convert_v1alpha1_OcpBuildDataGitSource_To_art_OcpBuildDataGitSource is an autogenerated conversion function.
func Convert_v1alpha1_OcpBuildDataGitSource_To_art_OcpBuildDataGitSource(in *OcpBuildDataGitSource, out *art.OcpBuildDataGitSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_OcpBuildDataGitSource_To_art_OcpBuildDataGitSource(in, out, s)
}

func autoConvert_art_OcpBuildDataGitSource_To_v1alpha1_OcpBuildDataGitSource(in *art.OcpBuildDataGitSource, out *OcpBuildDataGitSource, s conversion.Scope) error {
	out.Url = in.Url
	out.Ref = in.Ref
	out.Path = in.Path
	return nil
}

// Convert_art_OcpBuildDataGitSource_To_v1alpha1_OcpBuildDataGitSource is an autogenerated conversion function.
func Convert_art_OcpBuildDataGitSource_To_v1alpha1_OcpBuildDataGitSource(in *art.OcpBuildDataGitSource, out *OcpBuildDataGitSource, s conversion.Scope) error {
	return autoConvert_art_OcpBuildDataGitSource_To_v1alpha1_OcpBuildDataGitSource(in, out, s)
}

func autoConvert_v1alpha1_RPMCompose_To_art_RPMCompose(in *RPMCompose, out *art.RPMCompose, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RPMComposeSpec_To_art_RPMComposeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RPMComposeStatus_To_art_RPMComposeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RPMCompose_To_art_RPMCompose is an autogenerated conversion function.
func Convert_v1alpha1_RPMCompose_To_art_RPMCompose(in *RPMCompose, out *art.RPMCompose, s conversion.Scope) error {
	return autoConvert_v1alpha1_RPMCompose_To_art_RPMCompose(in, out, s)
}

func autoConvert_art_RPMCompose_To_v1alpha1_RPMCompose(in *art.RPMCompose, out *RPMCompose, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_art_RPMComposeSpec_To_v1alpha1_RPMComposeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_art_RPMComposeStatus_To_v1alpha1_RPMComposeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_art_RPMCompose_To_v1alpha1_RPMCompose is an autogenerated conversion function.
func Convert_art_RPMCompose_To_v1alpha1_RPMCompose(in *art.RPMCompose, out *RPMCompose, s conversion.Scope) error {
	return autoConvert_art_RPMCompose_To_v1alpha1_RPMCompose(in, out, s)
}

func autoConvert_v1alpha1_RPMComposeList_To_art_RPMComposeList(in *RPMComposeList, out *art.RPMComposeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]art.RPMCompose)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_RPMComposeList_To_art_RPMComposeList is an autogenerated conversion function.
func Convert_v1alpha1_RPMComposeList_To_art_RPMComposeList(in *RPMComposeList, out *art.RPMComposeList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RPMComposeList_To_art_RPMComposeList(in, out, s)
}

func autoConvert_art_RPMComposeList_To_v1alpha1_RPMComposeList(in *art.RPMComposeList, out *RPMComposeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]RPMCompose)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_art_RPMComposeList_To_v1alpha1_RPMComposeList is an autogenerated conversion function.
func Convert_art_RPMComposeList_To_v1alpha1_RPMComposeList(in *art.RPMComposeList, out *RPMComposeList, s conversion.Scope) error {
	return autoConvert_art_RPMComposeList_To_v1alpha1_RPMComposeList(in, out, s)
}

func autoConvert_v1alpha1_RPMComposeSpec_To_art_RPMComposeSpec(in *RPMComposeSpec, out *art.RPMComposeSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_RPMComposeSpec_To_art_RPMComposeSpec is an autogenerated conversion function.
func Convert_v1alpha1_RPMComposeSpec_To_art_RPMComposeSpec(in *RPMComposeSpec, out *art.RPMComposeSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RPMComposeSpec_To_art_RPMComposeSpec(in, out, s)
}

func autoConvert_art_RPMComposeSpec_To_v1alpha1_RPMComposeSpec(in *art.RPMComposeSpec, out *RPMComposeSpec, s conversion.Scope) error {
	return nil
}

// Convert_art_RPMComposeSpec_To_v1alpha1_RPMComposeSpec is an autogenerated conversion function.
func Convert_art_RPMComposeSpec_To_v1alpha1_RPMComposeSpec(in *art.RPMComposeSpec, out *RPMComposeSpec, s conversion.Scope) error {
	return autoConvert_art_RPMComposeSpec_To_v1alpha1_RPMComposeSpec(in, out, s)
}

func autoConvert_v1alpha1_RPMComposeStatus_To_art_RPMComposeStatus(in *RPMComposeStatus, out *art.RPMComposeStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_RPMComposeStatus_To_art_RPMComposeStatus is an autogenerated conversion function.
func Convert_v1alpha1_RPMComposeStatus_To_art_RPMComposeStatus(in *RPMComposeStatus, out *art.RPMComposeStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RPMComposeStatus_To_art_RPMComposeStatus(in, out, s)
}

func autoConvert_art_RPMComposeStatus_To_v1alpha1_RPMComposeStatus(in *art.RPMComposeStatus, out *RPMComposeStatus, s conversion.Scope) error {
	return nil
}

// Convert_art_RPMComposeStatus_To_v1alpha1_RPMComposeStatus is an autogenerated conversion function.
func Convert_art_RPMComposeStatus_To_v1alpha1_RPMComposeStatus(in *art.RPMComposeStatus, out *RPMComposeStatus, s conversion.Scope) error {
	return autoConvert_art_RPMComposeStatus_To_v1alpha1_RPMComposeStatus(in, out, s)
}

func autoConvert_v1alpha1_Release_To_art_Release(in *Release, out *art.Release, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ReleaseSpec_To_art_ReleaseSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ReleaseStatus_To_art_ReleaseStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Release_To_art_Release is an autogenerated conversion function.
func Convert_v1alpha1_Release_To_art_Release(in *Release, out *art.Release, s conversion.Scope) error {
	return autoConvert_v1alpha1_Release_To_art_Release(in, out, s)
}

func autoConvert_art_Release_To_v1alpha1_Release(in *art.Release, out *Release, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_art_ReleaseSpec_To_v1alpha1_ReleaseSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_art_ReleaseStatus_To_v1alpha1_ReleaseStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_art_Release_To_v1alpha1_Release is an autogenerated conversion function.
func Convert_art_Release_To_v1alpha1_Release(in *art.Release, out *Release, s conversion.Scope) error {
	return autoConvert_art_Release_To_v1alpha1_Release(in, out, s)
}

func autoConvert_v1alpha1_ReleaseList_To_art_ReleaseList(in *ReleaseList, out *art.ReleaseList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]art.Release)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ReleaseList_To_art_ReleaseList is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseList_To_art_ReleaseList(in *ReleaseList, out *art.ReleaseList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseList_To_art_ReleaseList(in, out, s)
}

func autoConvert_art_ReleaseList_To_v1alpha1_ReleaseList(in *art.ReleaseList, out *ReleaseList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Release)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_art_ReleaseList_To_v1alpha1_ReleaseList is an autogenerated conversion function.
func Convert_art_ReleaseList_To_v1alpha1_ReleaseList(in *art.ReleaseList, out *ReleaseList, s conversion.Scope) error {
	return autoConvert_art_ReleaseList_To_v1alpha1_ReleaseList(in, out, s)
}

func autoConvert_v1alpha1_ReleaseSpec_To_art_ReleaseSpec(in *ReleaseSpec, out *art.ReleaseSpec, s conversion.Scope) error {
	out.ReleaseStreamName = in.ReleaseStreamName
	if err := Convert_v1alpha1_ReleaseVersion_To_art_ReleaseVersion(&in.Version, &out.Version, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ReleaseSpec_To_art_ReleaseSpec is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseSpec_To_art_ReleaseSpec(in *ReleaseSpec, out *art.ReleaseSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseSpec_To_art_ReleaseSpec(in, out, s)
}

func autoConvert_art_ReleaseSpec_To_v1alpha1_ReleaseSpec(in *art.ReleaseSpec, out *ReleaseSpec, s conversion.Scope) error {
	out.ReleaseStreamName = in.ReleaseStreamName
	if err := Convert_art_ReleaseVersion_To_v1alpha1_ReleaseVersion(&in.Version, &out.Version, s); err != nil {
		return err
	}
	return nil
}

// Convert_art_ReleaseSpec_To_v1alpha1_ReleaseSpec is an autogenerated conversion function.
func Convert_art_ReleaseSpec_To_v1alpha1_ReleaseSpec(in *art.ReleaseSpec, out *ReleaseSpec, s conversion.Scope) error {
	return autoConvert_art_ReleaseSpec_To_v1alpha1_ReleaseSpec(in, out, s)
}

func autoConvert_v1alpha1_ReleaseStatus_To_art_ReleaseStatus(in *ReleaseStatus, out *art.ReleaseStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ReleaseStatus_To_art_ReleaseStatus is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseStatus_To_art_ReleaseStatus(in *ReleaseStatus, out *art.ReleaseStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseStatus_To_art_ReleaseStatus(in, out, s)
}

func autoConvert_art_ReleaseStatus_To_v1alpha1_ReleaseStatus(in *art.ReleaseStatus, out *ReleaseStatus, s conversion.Scope) error {
	return nil
}

// Convert_art_ReleaseStatus_To_v1alpha1_ReleaseStatus is an autogenerated conversion function.
func Convert_art_ReleaseStatus_To_v1alpha1_ReleaseStatus(in *art.ReleaseStatus, out *ReleaseStatus, s conversion.Scope) error {
	return autoConvert_art_ReleaseStatus_To_v1alpha1_ReleaseStatus(in, out, s)
}

func autoConvert_v1alpha1_ReleaseStream_To_art_ReleaseStream(in *ReleaseStream, out *art.ReleaseStream, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ReleaseStreamSpec_To_art_ReleaseStreamSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ReleaseStreamStatus_To_art_ReleaseStreamStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ReleaseStream_To_art_ReleaseStream is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseStream_To_art_ReleaseStream(in *ReleaseStream, out *art.ReleaseStream, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseStream_To_art_ReleaseStream(in, out, s)
}

func autoConvert_art_ReleaseStream_To_v1alpha1_ReleaseStream(in *art.ReleaseStream, out *ReleaseStream, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_art_ReleaseStreamSpec_To_v1alpha1_ReleaseStreamSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_art_ReleaseStreamStatus_To_v1alpha1_ReleaseStreamStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_art_ReleaseStream_To_v1alpha1_ReleaseStream is an autogenerated conversion function.
func Convert_art_ReleaseStream_To_v1alpha1_ReleaseStream(in *art.ReleaseStream, out *ReleaseStream, s conversion.Scope) error {
	return autoConvert_art_ReleaseStream_To_v1alpha1_ReleaseStream(in, out, s)
}

func autoConvert_v1alpha1_ReleaseStreamList_To_art_ReleaseStreamList(in *ReleaseStreamList, out *art.ReleaseStreamList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]art.ReleaseStream)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ReleaseStreamList_To_art_ReleaseStreamList is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseStreamList_To_art_ReleaseStreamList(in *ReleaseStreamList, out *art.ReleaseStreamList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseStreamList_To_art_ReleaseStreamList(in, out, s)
}

func autoConvert_art_ReleaseStreamList_To_v1alpha1_ReleaseStreamList(in *art.ReleaseStreamList, out *ReleaseStreamList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ReleaseStream)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_art_ReleaseStreamList_To_v1alpha1_ReleaseStreamList is an autogenerated conversion function.
func Convert_art_ReleaseStreamList_To_v1alpha1_ReleaseStreamList(in *art.ReleaseStreamList, out *ReleaseStreamList, s conversion.Scope) error {
	return autoConvert_art_ReleaseStreamList_To_v1alpha1_ReleaseStreamList(in, out, s)
}

func autoConvert_v1alpha1_ReleaseStreamOcpBuildData_To_art_ReleaseStreamOcpBuildData(in *ReleaseStreamOcpBuildData, out *art.ReleaseStreamOcpBuildData, s conversion.Scope) error {
	if err := Convert_v1alpha1_OcpBuildDataGitSource_To_art_OcpBuildDataGitSource(&in.Git, &out.Git, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ReleaseStreamOcpBuildData_To_art_ReleaseStreamOcpBuildData is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseStreamOcpBuildData_To_art_ReleaseStreamOcpBuildData(in *ReleaseStreamOcpBuildData, out *art.ReleaseStreamOcpBuildData, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseStreamOcpBuildData_To_art_ReleaseStreamOcpBuildData(in, out, s)
}

func autoConvert_art_ReleaseStreamOcpBuildData_To_v1alpha1_ReleaseStreamOcpBuildData(in *art.ReleaseStreamOcpBuildData, out *ReleaseStreamOcpBuildData, s conversion.Scope) error {
	if err := Convert_art_OcpBuildDataGitSource_To_v1alpha1_OcpBuildDataGitSource(&in.Git, &out.Git, s); err != nil {
		return err
	}
	return nil
}

// Convert_art_ReleaseStreamOcpBuildData_To_v1alpha1_ReleaseStreamOcpBuildData is an autogenerated conversion function.
func Convert_art_ReleaseStreamOcpBuildData_To_v1alpha1_ReleaseStreamOcpBuildData(in *art.ReleaseStreamOcpBuildData, out *ReleaseStreamOcpBuildData, s conversion.Scope) error {
	return autoConvert_art_ReleaseStreamOcpBuildData_To_v1alpha1_ReleaseStreamOcpBuildData(in, out, s)
}

func autoConvert_v1alpha1_ReleaseStreamSpec_To_art_ReleaseStreamSpec(in *ReleaseStreamSpec, out *art.ReleaseStreamSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ReleaseStreamOcpBuildData_To_art_ReleaseStreamOcpBuildData(&in.OcpBuildData, &out.OcpBuildData, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ReleaseStreamSpec_To_art_ReleaseStreamSpec is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseStreamSpec_To_art_ReleaseStreamSpec(in *ReleaseStreamSpec, out *art.ReleaseStreamSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseStreamSpec_To_art_ReleaseStreamSpec(in, out, s)
}

func autoConvert_art_ReleaseStreamSpec_To_v1alpha1_ReleaseStreamSpec(in *art.ReleaseStreamSpec, out *ReleaseStreamSpec, s conversion.Scope) error {
	if err := Convert_art_ReleaseStreamOcpBuildData_To_v1alpha1_ReleaseStreamOcpBuildData(&in.OcpBuildData, &out.OcpBuildData, s); err != nil {
		return err
	}
	return nil
}

// Convert_art_ReleaseStreamSpec_To_v1alpha1_ReleaseStreamSpec is an autogenerated conversion function.
func Convert_art_ReleaseStreamSpec_To_v1alpha1_ReleaseStreamSpec(in *art.ReleaseStreamSpec, out *ReleaseStreamSpec, s conversion.Scope) error {
	return autoConvert_art_ReleaseStreamSpec_To_v1alpha1_ReleaseStreamSpec(in, out, s)
}

func autoConvert_v1alpha1_ReleaseStreamStatus_To_art_ReleaseStreamStatus(in *ReleaseStreamStatus, out *art.ReleaseStreamStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ReleaseStreamStatus_To_art_ReleaseStreamStatus is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseStreamStatus_To_art_ReleaseStreamStatus(in *ReleaseStreamStatus, out *art.ReleaseStreamStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseStreamStatus_To_art_ReleaseStreamStatus(in, out, s)
}

func autoConvert_art_ReleaseStreamStatus_To_v1alpha1_ReleaseStreamStatus(in *art.ReleaseStreamStatus, out *ReleaseStreamStatus, s conversion.Scope) error {
	return nil
}

// Convert_art_ReleaseStreamStatus_To_v1alpha1_ReleaseStreamStatus is an autogenerated conversion function.
func Convert_art_ReleaseStreamStatus_To_v1alpha1_ReleaseStreamStatus(in *art.ReleaseStreamStatus, out *ReleaseStreamStatus, s conversion.Scope) error {
	return autoConvert_art_ReleaseStreamStatus_To_v1alpha1_ReleaseStreamStatus(in, out, s)
}

func autoConvert_v1alpha1_ReleaseVersion_To_art_ReleaseVersion(in *ReleaseVersion, out *art.ReleaseVersion, s conversion.Scope) error {
	out.Major = in.Major
	out.Minor = in.Minor
	out.Patch = in.Patch
	out.PreRelease = in.PreRelease
	return nil
}

// Convert_v1alpha1_ReleaseVersion_To_art_ReleaseVersion is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseVersion_To_art_ReleaseVersion(in *ReleaseVersion, out *art.ReleaseVersion, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseVersion_To_art_ReleaseVersion(in, out, s)
}

func autoConvert_art_ReleaseVersion_To_v1alpha1_ReleaseVersion(in *art.ReleaseVersion, out *ReleaseVersion, s conversion.Scope) error {
	out.Major = in.Major
	out.Minor = in.Minor
	out.Patch = in.Patch
	out.PreRelease = in.PreRelease
	return nil
}

// Convert_art_ReleaseVersion_To_v1alpha1_ReleaseVersion is an autogenerated conversion function.
func Convert_art_ReleaseVersion_To_v1alpha1_ReleaseVersion(in *art.ReleaseVersion, out *ReleaseVersion, s conversion.Scope) error {
	return autoConvert_art_ReleaseVersion_To_v1alpha1_ReleaseVersion(in, out, s)
}

func autoConvert_v1alpha1_SourceRevision_To_art_SourceRevision(in *SourceRevision, out *art.SourceRevision, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_SourceRevisionSpec_To_art_SourceRevisionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_SourceRevisionStatus_To_art_SourceRevisionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_SourceRevision_To_art_SourceRevision is an autogenerated conversion function.
func Convert_v1alpha1_SourceRevision_To_art_SourceRevision(in *SourceRevision, out *art.SourceRevision, s conversion.Scope) error {
	return autoConvert_v1alpha1_SourceRevision_To_art_SourceRevision(in, out, s)
}

func autoConvert_art_SourceRevision_To_v1alpha1_SourceRevision(in *art.SourceRevision, out *SourceRevision, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_art_SourceRevisionSpec_To_v1alpha1_SourceRevisionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_art_SourceRevisionStatus_To_v1alpha1_SourceRevisionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_art_SourceRevision_To_v1alpha1_SourceRevision is an autogenerated conversion function.
func Convert_art_SourceRevision_To_v1alpha1_SourceRevision(in *art.SourceRevision, out *SourceRevision, s conversion.Scope) error {
	return autoConvert_art_SourceRevision_To_v1alpha1_SourceRevision(in, out, s)
}

func autoConvert_v1alpha1_SourceRevisionList_To_art_SourceRevisionList(in *SourceRevisionList, out *art.SourceRevisionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]art.SourceRevision)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_SourceRevisionList_To_art_SourceRevisionList is an autogenerated conversion function.
func Convert_v1alpha1_SourceRevisionList_To_art_SourceRevisionList(in *SourceRevisionList, out *art.SourceRevisionList, s conversion.Scope) error {
	return autoConvert_v1alpha1_SourceRevisionList_To_art_SourceRevisionList(in, out, s)
}

func autoConvert_art_SourceRevisionList_To_v1alpha1_SourceRevisionList(in *art.SourceRevisionList, out *SourceRevisionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]SourceRevision)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_art_SourceRevisionList_To_v1alpha1_SourceRevisionList is an autogenerated conversion function.
func Convert_art_SourceRevisionList_To_v1alpha1_SourceRevisionList(in *art.SourceRevisionList, out *SourceRevisionList, s conversion.Scope) error {
	return autoConvert_art_SourceRevisionList_To_v1alpha1_SourceRevisionList(in, out, s)
}

func autoConvert_v1alpha1_SourceRevisionSpec_To_art_SourceRevisionSpec(in *SourceRevisionSpec, out *art.SourceRevisionSpec, s conversion.Scope) error {
	out.ComponentName = in.ComponentName
	out.CommitHash = in.CommitHash
	return nil
}

// Convert_v1alpha1_SourceRevisionSpec_To_art_SourceRevisionSpec is an autogenerated conversion function.
func Convert_v1alpha1_SourceRevisionSpec_To_art_SourceRevisionSpec(in *SourceRevisionSpec, out *art.SourceRevisionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_SourceRevisionSpec_To_art_SourceRevisionSpec(in, out, s)
}

func autoConvert_art_SourceRevisionSpec_To_v1alpha1_SourceRevisionSpec(in *art.SourceRevisionSpec, out *SourceRevisionSpec, s conversion.Scope) error {
	out.ComponentName = in.ComponentName
	out.CommitHash = in.CommitHash
	return nil
}

// Convert_art_SourceRevisionSpec_To_v1alpha1_SourceRevisionSpec is an autogenerated conversion function.
func Convert_art_SourceRevisionSpec_To_v1alpha1_SourceRevisionSpec(in *art.SourceRevisionSpec, out *SourceRevisionSpec, s conversion.Scope) error {
	return autoConvert_art_SourceRevisionSpec_To_v1alpha1_SourceRevisionSpec(in, out, s)
}

func autoConvert_v1alpha1_SourceRevisionStatus_To_art_SourceRevisionStatus(in *SourceRevisionStatus, out *art.SourceRevisionStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_SourceRevisionStatus_To_art_SourceRevisionStatus is an autogenerated conversion function.
func Convert_v1alpha1_SourceRevisionStatus_To_art_SourceRevisionStatus(in *SourceRevisionStatus, out *art.SourceRevisionStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_SourceRevisionStatus_To_art_SourceRevisionStatus(in, out, s)
}

func autoConvert_art_SourceRevisionStatus_To_v1alpha1_SourceRevisionStatus(in *art.SourceRevisionStatus, out *SourceRevisionStatus, s conversion.Scope) error {
	return nil
}

// Convert_art_SourceRevisionStatus_To_v1alpha1_SourceRevisionStatus is an autogenerated conversion function.
func Convert_art_SourceRevisionStatus_To_v1alpha1_SourceRevisionStatus(in *art.SourceRevisionStatus, out *SourceRevisionStatus, s conversion.Scope) error {
	return autoConvert_art_SourceRevisionStatus_To_v1alpha1_SourceRevisionStatus(in, out, s)
}
