/*
Copyright 2020 The OpenShift Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by apiregister-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/vfreex/release-apiserver/pkg/apis/art"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/apiserver-builder-alpha/pkg/builders"
)

func addKnownTypes(scheme *runtime.Scheme) error {
	// TODO this will get cleaned up with the scheme types are fixed
	scheme.AddKnownTypes(SchemeGroupVersion,
		&Advisory{},
		&AdvisoryList{},
		&Build{},
		&BuildList{},
		&Component{},
		&ComponentList{},
		&RPMCompose{},
		&RPMComposeList{},
		&Release{},
		&ReleaseList{},
		&ReleaseStream{},
		&ReleaseStreamList{},
		&SourceRevision{},
		&SourceRevisionList{},
	)
	return nil
}

var (
	ApiVersion = builders.NewApiVersion("art.openshift.io", "v1alpha1").WithResources(
		art.ArtAdvisoryStorage,
		builders.NewApiResource( // Resource status endpoint
			art.InternalAdvisoryStatus,
			func() runtime.Object { return &Advisory{} },     // Register versioned resource
			func() runtime.Object { return &AdvisoryList{} }, // Register versioned resource list
			&art.AdvisoryStatusStrategy{DefaultStatusStorageStrategy: builders.StatusStorageStrategySingleton},
		), art.ArtBuildStorage,
		builders.NewApiResource( // Resource status endpoint
			art.InternalBuildStatus,
			func() runtime.Object { return &Build{} },     // Register versioned resource
			func() runtime.Object { return &BuildList{} }, // Register versioned resource list
			&art.BuildStatusStrategy{DefaultStatusStorageStrategy: builders.StatusStorageStrategySingleton},
		), art.ArtComponentStorage,
		builders.NewApiResource( // Resource status endpoint
			art.InternalComponentStatus,
			func() runtime.Object { return &Component{} },     // Register versioned resource
			func() runtime.Object { return &ComponentList{} }, // Register versioned resource list
			&art.ComponentStatusStrategy{DefaultStatusStorageStrategy: builders.StatusStorageStrategySingleton},
		), art.ArtRPMComposeStorage,
		builders.NewApiResource( // Resource status endpoint
			art.InternalRPMComposeStatus,
			func() runtime.Object { return &RPMCompose{} },     // Register versioned resource
			func() runtime.Object { return &RPMComposeList{} }, // Register versioned resource list
			&art.RPMComposeStatusStrategy{DefaultStatusStorageStrategy: builders.StatusStorageStrategySingleton},
		), art.ArtReleaseStorage,
		builders.NewApiResource( // Resource status endpoint
			art.InternalReleaseStatus,
			func() runtime.Object { return &Release{} },     // Register versioned resource
			func() runtime.Object { return &ReleaseList{} }, // Register versioned resource list
			&art.ReleaseStatusStrategy{DefaultStatusStorageStrategy: builders.StatusStorageStrategySingleton},
		), art.ArtReleaseStreamStorage,
		builders.NewApiResource( // Resource status endpoint
			art.InternalReleaseStreamStatus,
			func() runtime.Object { return &ReleaseStream{} },     // Register versioned resource
			func() runtime.Object { return &ReleaseStreamList{} }, // Register versioned resource list
			&art.ReleaseStreamStatusStrategy{DefaultStatusStorageStrategy: builders.StatusStorageStrategySingleton},
		), art.ArtSourceRevisionStorage,
		builders.NewApiResource( // Resource status endpoint
			art.InternalSourceRevisionStatus,
			func() runtime.Object { return &SourceRevision{} },     // Register versioned resource
			func() runtime.Object { return &SourceRevisionList{} }, // Register versioned resource list
			&art.SourceRevisionStatusStrategy{DefaultStatusStorageStrategy: builders.StatusStorageStrategySingleton},
		))

	// Required by code generated by go2idl
	AddToScheme = (&runtime.SchemeBuilder{
		ApiVersion.SchemeBuilder.AddToScheme,
		RegisterDefaults,
		RegisterConversions,
		addKnownTypes,
		func(scheme *runtime.Scheme) error {
			metav1.AddToGroupVersion(scheme, SchemeGroupVersion)
			return nil
		},
	}).AddToScheme

	SchemeBuilder      = ApiVersion.SchemeBuilder
	localSchemeBuilder = SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AdvisoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	Items           []Advisory `json:"items" protobuf:"bytes,2,rep,name=items"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type BuildList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	Items           []Build `json:"items" protobuf:"bytes,2,rep,name=items"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type ComponentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	Items           []Component `json:"items" protobuf:"bytes,2,rep,name=items"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type RPMComposeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	Items           []RPMCompose `json:"items" protobuf:"bytes,2,rep,name=items"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type ReleaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	Items           []Release `json:"items" protobuf:"bytes,2,rep,name=items"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type ReleaseStreamList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	Items           []ReleaseStream `json:"items" protobuf:"bytes,2,rep,name=items"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type SourceRevisionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	Items           []SourceRevision `json:"items" protobuf:"bytes,2,rep,name=items"`
}
