/*
Copyright 2020 The OpenShift Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vfreex/release-apiserver/pkg/apis/art/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRPMComposes implements RPMComposeInterface
type FakeRPMComposes struct {
	Fake *FakeArtV1alpha1
	ns   string
}

var rpmcomposesResource = schema.GroupVersionResource{Group: "art.openshift.io", Version: "v1alpha1", Resource: "rpmcomposes"}

var rpmcomposesKind = schema.GroupVersionKind{Group: "art.openshift.io", Version: "v1alpha1", Kind: "RPMCompose"}

// Get takes name of the rPMCompose, and returns the corresponding rPMCompose object, and an error if there is any.
func (c *FakeRPMComposes) Get(name string, options v1.GetOptions) (result *v1alpha1.RPMCompose, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rpmcomposesResource, c.ns, name), &v1alpha1.RPMCompose{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RPMCompose), err
}

// List takes label and field selectors, and returns the list of RPMComposes that match those selectors.
func (c *FakeRPMComposes) List(opts v1.ListOptions) (result *v1alpha1.RPMComposeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rpmcomposesResource, rpmcomposesKind, c.ns, opts), &v1alpha1.RPMComposeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RPMComposeList{ListMeta: obj.(*v1alpha1.RPMComposeList).ListMeta}
	for _, item := range obj.(*v1alpha1.RPMComposeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rPMComposes.
func (c *FakeRPMComposes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rpmcomposesResource, c.ns, opts))

}

// Create takes the representation of a rPMCompose and creates it.  Returns the server's representation of the rPMCompose, and an error, if there is any.
func (c *FakeRPMComposes) Create(rPMCompose *v1alpha1.RPMCompose) (result *v1alpha1.RPMCompose, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rpmcomposesResource, c.ns, rPMCompose), &v1alpha1.RPMCompose{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RPMCompose), err
}

// Update takes the representation of a rPMCompose and updates it. Returns the server's representation of the rPMCompose, and an error, if there is any.
func (c *FakeRPMComposes) Update(rPMCompose *v1alpha1.RPMCompose) (result *v1alpha1.RPMCompose, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rpmcomposesResource, c.ns, rPMCompose), &v1alpha1.RPMCompose{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RPMCompose), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRPMComposes) UpdateStatus(rPMCompose *v1alpha1.RPMCompose) (*v1alpha1.RPMCompose, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rpmcomposesResource, "status", c.ns, rPMCompose), &v1alpha1.RPMCompose{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RPMCompose), err
}

// Delete takes name of the rPMCompose and deletes it. Returns an error if one occurs.
func (c *FakeRPMComposes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(rpmcomposesResource, c.ns, name), &v1alpha1.RPMCompose{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRPMComposes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rpmcomposesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.RPMComposeList{})
	return err
}

// Patch applies the patch and returns the patched rPMCompose.
func (c *FakeRPMComposes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RPMCompose, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rpmcomposesResource, c.ns, name, pt, data, subresources...), &v1alpha1.RPMCompose{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RPMCompose), err
}
