/*
Copyright 2020 The OpenShift Release APIServer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vfreex/release-apiserver/pkg/apis/art/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSourceRevisions implements SourceRevisionInterface
type FakeSourceRevisions struct {
	Fake *FakeArtV1alpha1
	ns   string
}

var sourcerevisionsResource = schema.GroupVersionResource{Group: "art.openshift.io", Version: "v1alpha1", Resource: "sourcerevisions"}

var sourcerevisionsKind = schema.GroupVersionKind{Group: "art.openshift.io", Version: "v1alpha1", Kind: "SourceRevision"}

// Get takes name of the sourceRevision, and returns the corresponding sourceRevision object, and an error if there is any.
func (c *FakeSourceRevisions) Get(name string, options v1.GetOptions) (result *v1alpha1.SourceRevision, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sourcerevisionsResource, c.ns, name), &v1alpha1.SourceRevision{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SourceRevision), err
}

// List takes label and field selectors, and returns the list of SourceRevisions that match those selectors.
func (c *FakeSourceRevisions) List(opts v1.ListOptions) (result *v1alpha1.SourceRevisionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sourcerevisionsResource, sourcerevisionsKind, c.ns, opts), &v1alpha1.SourceRevisionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SourceRevisionList{ListMeta: obj.(*v1alpha1.SourceRevisionList).ListMeta}
	for _, item := range obj.(*v1alpha1.SourceRevisionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sourceRevisions.
func (c *FakeSourceRevisions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sourcerevisionsResource, c.ns, opts))

}

// Create takes the representation of a sourceRevision and creates it.  Returns the server's representation of the sourceRevision, and an error, if there is any.
func (c *FakeSourceRevisions) Create(sourceRevision *v1alpha1.SourceRevision) (result *v1alpha1.SourceRevision, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sourcerevisionsResource, c.ns, sourceRevision), &v1alpha1.SourceRevision{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SourceRevision), err
}

// Update takes the representation of a sourceRevision and updates it. Returns the server's representation of the sourceRevision, and an error, if there is any.
func (c *FakeSourceRevisions) Update(sourceRevision *v1alpha1.SourceRevision) (result *v1alpha1.SourceRevision, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sourcerevisionsResource, c.ns, sourceRevision), &v1alpha1.SourceRevision{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SourceRevision), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSourceRevisions) UpdateStatus(sourceRevision *v1alpha1.SourceRevision) (*v1alpha1.SourceRevision, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sourcerevisionsResource, "status", c.ns, sourceRevision), &v1alpha1.SourceRevision{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SourceRevision), err
}

// Delete takes name of the sourceRevision and deletes it. Returns an error if one occurs.
func (c *FakeSourceRevisions) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sourcerevisionsResource, c.ns, name), &v1alpha1.SourceRevision{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSourceRevisions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sourcerevisionsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SourceRevisionList{})
	return err
}

// Patch applies the patch and returns the patched sourceRevision.
func (c *FakeSourceRevisions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SourceRevision, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sourcerevisionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SourceRevision{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SourceRevision), err
}
